import { Meeting, Template, User } from '@/types/demo';
import { FeatureFlags } from '@/types/flags';

type PilotFlag = keyof FeatureFlags;

export interface PersonaMetadata extends User {
  authorityLabel?: string;
  focusArea?: string;
  /**
   * High-level function/vertical label shown on persona selection badges.
   */
  functionLabel?: string;
  /**
   * Feature flags that should surface a pilot/beta badge on this persona card.
   */
  pilotFlags?: PilotFlag[];
  /**
   * Optional text that appears inside the pilot badge.
   */
  pilotLabel?: string;
}

export const PERSONAS: Record<string, PersonaMetadata> = {
  sarah: {
    id: 'sarah',
    name: 'Sarah Jenkins',
    role: 'social_worker',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    email: 'sarah.jenkins@westminster.gov.uk',
    domain: 'children',
    team: 'Family Services (WCC)',
    functionLabel: 'Practitioner',
    authorityLabel: 'Westminster City Council',
    focusArea: 'Frontline child protection & statutory visits (Westminster Sovereign)',
  },
  nina: {
    id: 'nina',
    name: 'Nina Alvarez',
    role: 'social_worker',
    avatar: 'https://i.pravatar.cc/150?u=nina-rbkc',
    email: 'nina.alvarez@rbkc.gov.uk',
    domain: 'adults',
    team: 'Hospital Discharge (RBKC)',
    functionLabel: 'Practitioner',
    authorityLabel: 'Royal Borough of Kensington & Chelsea',
    focusArea: 'Adult assessments & care planning (RBKC Sovereign)',
  },
  david: {
    id: 'david',
    name: 'David Okafor',
    role: 'manager',
    avatar: 'https://i.pravatar.cc/150?u=david-rbkc',
    email: 'david.okafor@rbkc.gov.uk',
    domain: 'adults',
    team: 'Adult Social Care (Bi-Borough)',
    functionLabel: 'Team Manager',
    pilotFlags: ['aiInsights'],
    pilotLabel: 'AI Insights Beta',
    authorityLabel: 'Bi-Borough Adult Social Care',
    focusArea: 'Team supervision & case approvals (Shared Service)',
  },
  priya: {
    id: 'priya',
    name: 'Priya Patel',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?u=priya',
    email: 'priya.patel@westminster.gov.uk',
    domain: 'corporate',
    team: 'Digital & Innovation',
    functionLabel: 'Digital Lead',
    authorityLabel: 'Westminster City Council',
    focusArea: 'System configuration & module management (Corporate)',
  },
  marcus: {
    id: 'marcus',
    name: 'Marcus Thorne',
    role: 'housing_officer',
    avatar: 'https://i.pravatar.cc/150?u=marcus-thorne',
    email: 'marcus.thorne@rbkc.gov.uk',
    domain: 'housing',
    team: 'North Kensington Housing',
    functionLabel: 'Housing Officer',
    pilotFlags: ['housingPilot'],
    pilotLabel: 'Housing Pilot',
    authorityLabel: 'Royal Borough of Kensington & Chelsea',
    focusArea: 'Housing inspections & tenant audits (RBKC)',
  },
  elena: {
    id: 'elena',
    name: 'Elena Rossi',
    role: 'manager',
    avatar: 'https://i.pravatar.cc/150?u=elena-emergency',
    email: 'elena.rossi@westminster.gov.uk',
    domain: 'children',
    team: 'Children\'s Services',
    functionLabel: 'Team Manager',
    authorityLabel: 'Westminster City Council',
    focusArea: 'Service oversight & case reviews (Westminster)',
  },
};

export const TEMPLATES: Template[] = [
  {
    id: 'statutory-visit',
    name: 'Statutory Visit',
    description: 'Standard template for child statutory visits (Section 47).',
    icon: 'UserCheck',
    sections: ['Purpose of Visit', 'Child\'s Voice', 'Observations', 'Analysis', 'Actions'],
    domain: 'children',
  },
  {
    id: 'core-group',
    name: 'Core Group Meeting',
    description: 'Multi-agency meeting to review child protection plan.',
    icon: 'Users',
    sections: ['Review of Plan', 'Updates from Professionals', 'Family Update', 'Risk Analysis', 'Next Steps'],
    domain: 'children',
  },
  {
    id: 'care-assessment',
    name: 'Care Assessment',
    description: 'Comprehensive assessment of adult care needs.',
    icon: 'ClipboardList',
    sections: ['Personal History', 'Health Needs', 'Social Context', 'Capacity Assessment', 'Recommendations'],
    domain: 'adults',
  },
  {
    id: 'safeguarding',
    name: 'Safeguarding Strategy',
    description: 'Initial strategy discussion for safeguarding concerns.',
    icon: 'ShieldAlert',
    sections: ['Allegation Details', 'Immediate Risks', 'Agency Checks', 'Action Plan'],
    domain: 'adults',
  },
  {
    id: 'housing-inspection',
    name: 'Property Inspection',
    description: 'Standard housing condition inspection.',
    icon: 'Home',
    sections: ['Property Details', 'Tenant Feedback', 'Condition Report', 'Hazards (HHSRS)', 'Required Works'],
    domain: 'housing',
  },
];

export const MEETINGS: Meeting[] = [
  {
    id: 'm1',
    title: 'Smith Family - Statutory Visit',
    date: '2026-04-14T10:30:00',
    duration: '45m',
    attendees: ['Sarah Jenkins', 'Mrs. Smith', 'Tommy Smith'],
    templateId: 'statutory-visit',
    status: 'draft',
    domain: 'children',
    tags: ['Child Protection', 'Home Visit'],
    riskScore: 'medium',
    summary: 'Visit focused on school attendance barriers. Mother expressed concern about transport costs. Tommy appeared withdrawn but engaged when discussing football. Home conditions were adequate.',
    transcript: [
      { speaker: 'Sarah', text: 'Hi Mrs. Smith, thanks for letting me visit today. How have things been since last week?', timestamp: '00:05' },
      { speaker: 'Mrs. Smith', text: 'A bit better, honestly. Tommy\'s been going to school mostly, but the bus fare is getting really expensive.', timestamp: '00:12' },
      { speaker: 'Sarah', text: 'I understand. Have you applied for the travel assistance we discussed?', timestamp: '00:25' },
      { speaker: 'Mrs. Smith', text: 'I tried, but the form was confusing. I didn\'t know what to put for the income section.', timestamp: '00:35' },
    ],
    tasks: [
      { id: 't1', title: 'Assist with travel application', status: 'todo', assigneeId: 'sarah', dueDate: '2026-04-18' },
      { id: 't2', title: 'Check school attendance records', status: 'done', assigneeId: 'sarah', dueDate: '2026-04-14' },
    ],
    processingMode: 'fast',
    submittedBy: 'Sarah Jenkins',
    submittedById: 'sarah',
    submittedAt: '2026-04-14T11:30:00',
  },
  {
    id: 'm2',
    title: 'Core Group Meeting - Child A',
    date: '2026-04-16T14:00:00',
    duration: '01:15:00',
    attendees: ['Sarah Jenkins', 'School Rep', 'Health Visitor'],
    templateId: 'core-group',
    status: 'ready',
    domain: 'children',
    tags: ['Core Group', 'Multi-agency'],
    riskScore: 'high',
    summary: 'Review of the child protection plan. Attendance at school has improved to 92%. Health visitor reports normal development. Mother requested support with housing application.',
    transcript: [],
    tasks: [],
    processingMode: 'economy',
    submittedBy: 'Sarah Jenkins',
    submittedById: 'sarah',
    submittedAt: '2026-04-16T15:20:00',
  },
  {
    id: 'm3',
    title: 'Strategy Discussion - New Referral',
    date: '2026-04-15T09:30:00',
    duration: '30:00',
    attendees: ['David Okafor', 'Police Rep', 'Health Rep'],
    summary: 'Strategy discussion regarding new referral for physical abuse. Decision made to proceed with Section 47 enquiry.',
    transcript: [],
    status: 'ready',
    templateId: 'safeguarding',
    domain: 'adults',
    tags: ['Urgent', 'Strategy'],
    riskScore: 'high',
    tasks: [],
    processingMode: 'fast',
    submittedBy: 'David Okafor',
    submittedById: 'david',
    submittedAt: '2026-04-15T10:00:00',
  },
  {
    id: 'm4',
    title: 'Safeguarding Strategy - Case #8821',
    date: '2026-04-10T11:00:00',
    duration: '30m',
    attendees: ['David Okafor', 'Police Liaison', 'GP'],
    templateId: 'safeguarding',
    status: 'flagged',
    domain: 'adults',
    tags: ['Urgent', 'Strategy'],
    riskScore: 'high',
    summary: 'Initial strategy discussion regarding financial abuse allegations. Police to investigate bank statements. Immediate welfare check required.',
    transcript: [],
    tasks: [],
    processingMode: 'economy',
    submittedBy: 'David Okafor',
    submittedById: 'david',
    submittedAt: '2026-04-10T12:00:00',
    lastAction: 'returned',
    lastActionAt: '2026-04-11T09:00:00',
    lastActionBy: 'Manager QA',
  },
  {
    id: 'm5',
    title: 'Hospital Discharge Assessment - Mr. Jones',
    date: '2026-04-17T10:00:00',
    duration: '1h 15m',
    attendees: ['Nina Alvarez', 'Mr. Jones', 'Ward Sister'],
    templateId: 'care-assessment',
    status: 'ready',
    domain: 'adults',
    tags: ['Hospital Discharge', 'Assessment'],
    riskScore: 'medium',
    summary: 'Assessment for discharge planning. Patient requires package of care 4x daily. OT assessment completed. Family supportive but live distance away.',
    transcript: [],
    tasks: [],
    processingMode: 'fast',
    submittedBy: 'Nina Alvarez',
    submittedById: 'nina',
    submittedAt: '2026-04-17T11:30:00',
  },
  {
    id: 'm6',
    title: 'Care Review - Mrs. Patel',
    date: '2026-04-18T14:00:00',
    duration: '45m',
    attendees: ['Nina Alvarez', 'Mrs. Patel', 'Daughter'],
    templateId: 'care-assessment',
    status: 'approved',
    domain: 'adults',
    tags: ['Review', 'Community'],
    riskScore: 'low',
    summary: 'Annual review of care package. Current provision remains appropriate. User expressed satisfaction with carers.',
    transcript: [],
    tasks: [],
    processingMode: 'economy',
    submittedBy: 'Nina Alvarez',
    submittedById: 'nina',
    submittedAt: '2026-04-18T15:00:00',
  },
];
