// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from '@hey-api/client-next'
import type {
  ListTranscriptionsTranscriptionsGetData,
  ListTranscriptionsTranscriptionsGetResponses,
  ListTranscriptionsTranscriptionsGetErrors,
  CreateTranscriptionTranscriptionsPostData,
  CreateTranscriptionTranscriptionsPostResponses,
  CreateTranscriptionTranscriptionsPostErrors,
  CreateRecordingRecordingsPostData,
  CreateRecordingRecordingsPostResponses,
  CreateRecordingRecordingsPostErrors,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors,
  GetTranscriptionTranscriptionsTranscriptionIdGetData,
  GetTranscriptionTranscriptionsTranscriptionIdGetResponses,
  GetTranscriptionTranscriptionsTranscriptionIdGetErrors,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchData,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponses,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchErrors,
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData,
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponses,
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetErrors,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponses,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostErrors,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors,
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetData,
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponses,
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetErrors,
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData,
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponses,
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetErrors,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponses,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostErrors,
  GetDialogueTranscriptionsTranscriptionIdDialogueGetData,
  GetDialogueTranscriptionsTranscriptionIdDialogueGetResponses,
  GetDialogueTranscriptionsTranscriptionIdDialogueGetErrors,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponses,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchErrors,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponses,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostErrors,
  GetUserUsersMeGetData,
  GetUserUsersMeGetResponses,
  GetUserUsersMeGetErrors,
  UpdateDataRetentionUsersDataRetentionPatchData,
  UpdateDataRetentionUsersDataRetentionPatchResponses,
  UpdateDataRetentionUsersDataRetentionPatchErrors,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors,
  GetMinuteMinutesMinutesIdGetData,
  GetMinuteMinutesMinutesIdGetResponses,
  GetMinuteMinutesMinutesIdGetErrors,
  ListMinuteVersionsMinutesMinuteIdVersionsGetData,
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponses,
  ListMinuteVersionsMinutesMinuteIdVersionsGetErrors,
  CreateMinuteVersionMinutesMinuteIdVersionsPostData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponses,
  CreateMinuteVersionMinutesMinuteIdVersionsPostErrors,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors,
  ListMinuteTasksMinutesMinuteIdTasksGetData,
  ListMinuteTasksMinutesMinuteIdTasksGetResponses,
  ListMinuteTasksMinutesMinuteIdTasksGetErrors,
  CreateMinuteTaskMinutesMinuteIdTasksPostData,
  CreateMinuteTaskMinutesMinuteIdTasksPostResponses,
  CreateMinuteTaskMinutesMinuteIdTasksPostErrors,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchResponses,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchErrors,
  PushMinuteTasksMinutesMinuteIdTasksPushPostData,
  PushMinuteTasksMinutesMinuteIdTasksPushPostResponses,
  PushMinuteTasksMinutesMinuteIdTasksPushPostErrors,
  ExportMinuteMinutesMinuteIdExportPostData,
  ExportMinuteMinutesMinuteIdExportPostResponses,
  ExportMinuteMinutesMinuteIdExportPostErrors,
  GetTemplatesTemplatesGetData,
  GetTemplatesTemplatesGetResponses,
  GetTemplatesTemplatesGetErrors,
  GetUserTemplatesUserTemplatesGetData,
  GetUserTemplatesUserTemplatesGetResponses,
  GetUserTemplatesUserTemplatesGetErrors,
  CreateUserTemplateUserTemplatesPostData,
  CreateUserTemplateUserTemplatesPostResponses,
  CreateUserTemplateUserTemplatesPostErrors,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors,
  GetUserTemplateUserTemplatesTemplateIdGetData,
  GetUserTemplateUserTemplatesTemplateIdGetResponses,
  GetUserTemplateUserTemplatesTemplateIdGetErrors,
  EditUserTemplateUserTemplatesTemplateIdPatchData,
  EditUserTemplateUserTemplatesTemplateIdPatchResponses,
  EditUserTemplateUserTemplatesTemplateIdPatchErrors,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors,
  GetTenantConfigConfigTenantIdGetData,
  GetTenantConfigConfigTenantIdGetResponses,
  GetTenantConfigConfigTenantIdGetErrors,
  GetUserModulesModulesGetData,
  GetUserModulesModulesGetResponses,
  GetUserModulesModulesGetErrors,
  CheckAdminAccessAdminCheckAccessGetData,
  CheckAdminAccessAdminCheckAccessGetResponses,
  CheckAdminAccessAdminCheckAccessGetErrors,
  ListConfigsAdminConfigsGetData,
  ListConfigsAdminConfigsGetResponses,
  ListConfigsAdminConfigsGetErrors,
  GetConfigDetailAdminConfigsTenantIdGetData,
  GetConfigDetailAdminConfigsTenantIdGetResponses,
  GetConfigDetailAdminConfigsTenantIdGetErrors,
  GetConfigAuditAdminConfigsTenantIdAuditGetData,
  GetConfigAuditAdminConfigsTenantIdAuditGetResponses,
  GetConfigAuditAdminConfigsTenantIdAuditGetErrors,
  GetConfigHistoryAdminConfigsTenantIdHistoryGetData,
  GetConfigHistoryAdminConfigsTenantIdHistoryGetResponses,
  GetConfigHistoryAdminConfigsTenantIdHistoryGetErrors,
  ListMyTasksTasksGetData,
  ListMyTasksTasksGetResponses,
  ListMyTasksTasksGetErrors,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors,
  ListChatTranscriptionsTranscriptionIdChatGetData,
  ListChatTranscriptionsTranscriptionIdChatGetResponses,
  ListChatTranscriptionsTranscriptionIdChatGetErrors,
  CreateChatTranscriptionsTranscriptionIdChatPostData,
  CreateChatTranscriptionsTranscriptionIdChatPostResponses,
  CreateChatTranscriptionsTranscriptionIdChatPostErrors,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors,
} from './types.gen'
import { client as _heyApiClient } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * List Transcriptions
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTranscriptionsTranscriptionsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTranscriptionsTranscriptionsGetResponses,
    ListTranscriptionsTranscriptionsGetErrors,
    ThrowOnError
  >({
    url: '/transcriptions',
    ...options,
  })
}

/**
 * Create Transcription
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTranscriptionTranscriptionsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTranscriptionTranscriptionsPostResponses,
    CreateTranscriptionTranscriptionsPostErrors,
    ThrowOnError
  >({
    url: '/transcriptions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Create Recording
 */
export const createRecordingRecordingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRecordingRecordingsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateRecordingRecordingsPostResponses,
    CreateRecordingRecordingsPostErrors,
    ThrowOnError
  >({
    url: '/recordings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Transcription
 * Delete a specific transcription by ID.
 */
export const deleteTranscriptionTranscriptionsTranscriptionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses,
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}',
    ...options,
  })
}

/**
 * Get Transcription
 * Get a specific transcription by ID.
 */
export const getTranscriptionTranscriptionsTranscriptionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTranscriptionTranscriptionsTranscriptionIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetTranscriptionTranscriptionsTranscriptionIdGetResponses,
    GetTranscriptionTranscriptionsTranscriptionIdGetErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}',
    ...options,
  })
}

/**
 * Save Transcription
 * Save or update a transcription.
 */
export const saveTranscriptionTranscriptionsTranscriptionIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SaveTranscriptionTranscriptionsTranscriptionIdPatchData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    SaveTranscriptionTranscriptionsTranscriptionIdPatchResponses,
    SaveTranscriptionTranscriptionsTranscriptionIdPatchErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Transcription Translations
 */
export const getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).get<
      GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponses,
      GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/translations',
      ...options,
    })
  }

/**
 * Request Transcription Translation
 */
export const requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).post<
      RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponses,
      RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/translate',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

/**
 * Get Recordings For Transcription
 */
export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).get<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/recordings',
      ...options,
    })
  }

/**
 * Get Signed Recording
 */
export const getSignedRecordingRecordingsRecordingIdSignedUrlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetSignedRecordingRecordingsRecordingIdSignedUrlGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponses,
    GetSignedRecordingRecordingsRecordingIdSignedUrlGetErrors,
    ThrowOnError
  >({
    url: '/recordings/{recording_id}/signed-url',
    ...options,
  })
}

/**
 * Get Signed Recording Range
 */
export const getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).get<
      GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponses,
      GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/recordings/{recording_id}/signed-url-range',
      ...options,
    })
  }

/**
 * Record Evidence Click
 */
export const recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).post<
      RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponses,
      RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/evidence-click',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

/**
 * Get Dialogue
 */
export const getDialogueTranscriptionsTranscriptionIdDialogueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDialogueTranscriptionsTranscriptionIdDialogueGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetDialogueTranscriptionsTranscriptionIdDialogueGetResponses,
    GetDialogueTranscriptionsTranscriptionIdDialogueGetErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/dialogue',
    ...options,
  })
}

/**
 * Update Dialogue
 */
export const updateDialogueTranscriptionsTranscriptionIdDialoguePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponses,
    UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/dialogue',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Submit Feedback
 */
export const submitFeedbackTranscriptionsTranscriptionIdFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponses,
    SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/feedback',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get User
 */
export const getUserUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserUsersMeGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserUsersMeGetResponses,
    GetUserUsersMeGetErrors,
    ThrowOnError
  >({
    url: '/users/me',
    ...options,
  })
}

/**
 * Update Data Retention
 * Update the data retention period for the current user.
 *
 * Args:
 * data: Request body containing data_retention_days
 * current_user: The current authenticated user
 */
export const updateDataRetentionUsersDataRetentionPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateDataRetentionUsersDataRetentionPatchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDataRetentionUsersDataRetentionPatchResponses,
    UpdateDataRetentionUsersDataRetentionPatchErrors,
    ThrowOnError
  >({
    url: '/users/data-retention',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * List Minutes For Transcription
 */
export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
      ThrowOnError
    >
  ) => {
    return (options.client ?? _heyApiClient).get<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors,
      ThrowOnError
    >({
      url: '/transcription/{transcription_id}/minutes',
      ...options,
    })
  }

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses,
    CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors,
    ThrowOnError
  >({
    url: '/transcription/{transcription_id}/minutes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Minute
 */
export const getMinuteMinutesMinutesIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMinuteMinutesMinutesIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetMinuteMinutesMinutesIdGetResponses,
    GetMinuteMinutesMinutesIdGetErrors,
    ThrowOnError
  >({
    url: '/minutes/{minutes_id}',
    ...options,
  })
}

/**
 * List Minute Versions
 */
export const listMinuteVersionsMinutesMinuteIdVersionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListMinuteVersionsMinutesMinuteIdVersionsGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponses,
    ListMinuteVersionsMinutesMinuteIdVersionsGetErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/versions',
    ...options,
  })
}

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMinuteVersionMinutesMinuteIdVersionsPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMinuteVersionMinutesMinuteIdVersionsPostResponses,
    CreateMinuteVersionMinutesMinuteIdVersionsPostErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/versions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Minute Version
 */
export const deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses,
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors,
    ThrowOnError
  >({
    url: '/minute_versions/{minute_version_id}',
    ...options,
  })
}

/**
 * Get Minute Version
 */
export const getMinuteVersionMinuteVersionsMinuteVersionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors,
    ThrowOnError
  >({
    url: '/minute_versions/{minute_version_id}',
    ...options,
  })
}

/**
 * List Minute Tasks
 */
export const listMinuteTasksMinutesMinuteIdTasksGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListMinuteTasksMinutesMinuteIdTasksGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ListMinuteTasksMinutesMinuteIdTasksGetResponses,
    ListMinuteTasksMinutesMinuteIdTasksGetErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/tasks',
    ...options,
  })
}

/**
 * Create Minute Task
 */
export const createMinuteTaskMinutesMinuteIdTasksPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMinuteTaskMinutesMinuteIdTasksPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMinuteTaskMinutesMinuteIdTasksPostResponses,
    CreateMinuteTaskMinutesMinuteIdTasksPostErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/tasks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Patch Minute Task
 */
export const patchMinuteTaskMinutesMinuteIdTasksTaskIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchResponses,
    PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/tasks/{task_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Push Minute Tasks
 */
export const pushMinuteTasksMinutesMinuteIdTasksPushPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PushMinuteTasksMinutesMinuteIdTasksPushPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    PushMinuteTasksMinutesMinuteIdTasksPushPostResponses,
    PushMinuteTasksMinutesMinuteIdTasksPushPostErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/tasks/push',
    ...options,
  })
}

/**
 * Export Minute
 */
export const exportMinuteMinutesMinuteIdExportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExportMinuteMinutesMinuteIdExportPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ExportMinuteMinutesMinuteIdExportPostResponses,
    ExportMinuteMinutesMinuteIdExportPostErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/export',
    ...options,
  })
}

/**
 * Get Templates
 * Get metadata for all templates.
 */
export const getTemplatesTemplatesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTemplatesTemplatesGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetTemplatesTemplatesGetResponses,
    GetTemplatesTemplatesGetErrors,
    ThrowOnError
  >({
    url: '/templates',
    ...options,
  })
}

/**
 * Get User Templates
 */
export const getUserTemplatesUserTemplatesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetUserTemplatesUserTemplatesGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserTemplatesUserTemplatesGetResponses,
    GetUserTemplatesUserTemplatesGetErrors,
    ThrowOnError
  >({
    url: '/user-templates',
    ...options,
  })
}

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserTemplateUserTemplatesPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateUserTemplateUserTemplatesPostResponses,
    CreateUserTemplateUserTemplatesPostErrors,
    ThrowOnError
  >({
    url: '/user-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete User Template
 */
export const deleteUserTemplateUserTemplatesTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses,
    DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors,
    ThrowOnError
  >({
    url: '/user-templates/{template_id}',
    ...options,
  })
}

/**
 * Get User Template
 */
export const getUserTemplateUserTemplatesTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserTemplateUserTemplatesTemplateIdGetResponses,
    GetUserTemplateUserTemplatesTemplateIdGetErrors,
    ThrowOnError
  >({
    url: '/user-templates/{template_id}',
    ...options,
  })
}

/**
 * Edit User Template
 */
export const editUserTemplateUserTemplatesTemplateIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    EditUserTemplateUserTemplatesTemplateIdPatchData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    EditUserTemplateUserTemplatesTemplateIdPatchResponses,
    EditUserTemplateUserTemplatesTemplateIdPatchErrors,
    ThrowOnError
  >({
    url: '/user-templates/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses,
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors,
    ThrowOnError
  >({
    url: '/user-templates/{template_id}/duplicate',
    ...options,
  })
}

/**
 * Get Tenant Config
 */
export const getTenantConfigConfigTenantIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTenantConfigConfigTenantIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTenantConfigConfigTenantIdGetResponses,
    GetTenantConfigConfigTenantIdGetErrors,
    ThrowOnError
  >({
    url: '/config/{tenant_id}',
    ...options,
  })
}

/**
 * Get User Modules
 * Returns modules and navigation items for the current user's service_domain and role.
 *
 * Filters by:
 * - user.service_domain_id (from UserOrgRole table)
 * - user.role (from UserOrgRole table)
 * - tenant config (config*.yaml)
 *
 * Returns:
 * - modules: List of module manifests (id, label, icon, routes, deps, feature flags)
 * - navigation: List of navigation items with labels, hrefs, icons
 * - service_domain: Current user's domain
 * - role: Current user's role
 */
export const getUserModulesModulesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserModulesModulesGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserModulesModulesGetResponses,
    GetUserModulesModulesGetErrors,
    ThrowOnError
  >({
    url: '/modules',
    ...options,
  })
}

/**
 * Check Admin Access
 * Check if current user has admin access.
 */
export const checkAdminAccessAdminCheckAccessGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CheckAdminAccessAdminCheckAccessGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    CheckAdminAccessAdminCheckAccessGetResponses,
    CheckAdminAccessAdminCheckAccessGetErrors,
    ThrowOnError
  >({
    url: '/admin/check-access',
    ...options,
  })
}

/**
 * List Configs
 * List all available tenant configurations.
 */
export const listConfigsAdminConfigsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListConfigsAdminConfigsGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ListConfigsAdminConfigsGetResponses,
    ListConfigsAdminConfigsGetErrors,
    ThrowOnError
  >({
    url: '/admin/configs',
    ...options,
  })
}

/**
 * Get Config Detail
 * Get detailed configuration for a specific tenant.
 */
export const getConfigDetailAdminConfigsTenantIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetConfigDetailAdminConfigsTenantIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetConfigDetailAdminConfigsTenantIdGetResponses,
    GetConfigDetailAdminConfigsTenantIdGetErrors,
    ThrowOnError
  >({
    url: '/admin/configs/{tenant_id}',
    ...options,
  })
}

/**
 * Get Config Audit
 * Get audit trail for a specific tenant configuration.
 */
export const getConfigAuditAdminConfigsTenantIdAuditGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetConfigAuditAdminConfigsTenantIdAuditGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetConfigAuditAdminConfigsTenantIdAuditGetResponses,
    GetConfigAuditAdminConfigsTenantIdAuditGetErrors,
    ThrowOnError
  >({
    url: '/admin/configs/{tenant_id}/audit',
    ...options,
  })
}

/**
 * Get Config History
 * Get version history for a specific tenant configuration.
 */
export const getConfigHistoryAdminConfigsTenantIdHistoryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetConfigHistoryAdminConfigsTenantIdHistoryGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetConfigHistoryAdminConfigsTenantIdHistoryGetResponses,
    GetConfigHistoryAdminConfigsTenantIdHistoryGetErrors,
    ThrowOnError
  >({
    url: '/admin/configs/{tenant_id}/history',
    ...options,
  })
}

/**
 * List My Tasks
 */
export const listMyTasksTasksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListMyTasksTasksGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListMyTasksTasksGetResponses,
    ListMyTasksTasksGetErrors,
    ThrowOnError
  >({
    url: '/tasks',
    ...options,
  })
}

/**
 * Delete Chats
 */
export const deleteChatsTranscriptionsTranscriptionIdChatDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses,
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat',
    ...options,
  })
}

/**
 * List Chat
 */
export const listChatTranscriptionsTranscriptionIdChatGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListChatTranscriptionsTranscriptionIdChatGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ListChatTranscriptionsTranscriptionIdChatGetResponses,
    ListChatTranscriptionsTranscriptionIdChatGetErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat',
    ...options,
  })
}

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateChatTranscriptionsTranscriptionIdChatPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChatTranscriptionsTranscriptionIdChatPostResponses,
    CreateChatTranscriptionsTranscriptionIdChatPostErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Chat
 * Delete a specific transcription by ID.
 */
export const deleteChatTranscriptionsTranscriptionIdChatChatIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses,
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat/{chat_id}',
    ...options,
  })
}

/**
 * Get Chat
 */
export const getChatTranscriptionsTranscriptionIdChatChatIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat/{chat_id}',
    ...options,
  })
}
