/**
 * Insights Analytics Types
 * 
 * Type definitions for team performance, adoption metrics, and workload distribution.
 * Used throughout the insights dashboard and analytics features.
 */

/** Period options for date range filtering */
export type InsightPeriod = 'today' | 'week' | 'month' | 'quarter' | 'year';

/** Period option with label for UI display */
export interface PeriodOption {
  value: InsightPeriod;
  label: string;
  days: number;
}

/** Available period options */
export const PERIOD_OPTIONS: PeriodOption[] = [
  { value: 'today', label: 'Today', days: 1 },
  { value: 'week', label: 'This Week', days: 7 },
  { value: 'month', label: 'This Month', days: 30 },
  { value: 'quarter', label: 'This Quarter', days: 90 },
  { value: 'year', label: 'This Year', days: 365 },
];

/** Team-level aggregate metrics */
export interface TeamMetrics {
  /** Total number of recordings in the period */
  totalRecordings: number;
  /** Average recording duration in minutes */
  avgDuration: number;
  /** Percentage of recordings completed (approved/ready) */
  completionRate: number;
  /** Total minutes of audio processed */
  totalAudioMinutes: number;
  /** Average time from upload to approval in hours */
  avgTurnaroundTime: number;
  /** Number of unique users who recorded */
  activeUsers: number;
  /** Change from previous period (percentage) */
  changeFromPrevious: {
    recordings: number;
    duration: number;
    completionRate: number;
  };
}

/** Individual user metrics */
export interface UserMetrics {
  userId: string;
  userName: string;
  userRole: string;
  userAvatar?: string;
  /** Total recordings by this user */
  recordings: number;
  /** Total minutes generated by this user */
  minutes: number;
  /** Average time for review in hours */
  avgReviewTime: number;
  /** Number of approved items */
  approved: number;
  /** Number of flagged/returned items */
  flagged: number;
  /** Completion rate percentage */
  completionRate: number;
  /** Last activity timestamp */
  lastActivity: string | null;
}

/** Sentiment analysis counts */
export interface SentimentTrend {
  positive: number;
  neutral: number;
  negative: number;
  /** Breakdown by category/topic if available */
  byCategory?: Record<string, { positive: number; neutral: number; negative: number }>;
}

/** Workload distribution data */
export interface WorkloadData {
  /** Workload by user - userId to count */
  byUser: Record<string, number>;
  /** Workload by day of week - 0 (Sunday) to 6 (Saturday) */
  byDay: Record<number, number>;
  /** Workload by domain/service area */
  byDomain: Record<string, number>;
  /** Workload by hour of day - 0 to 23 */
  byHour: Record<number, number>;
}

/** Heatmap cell data */
export interface HeatmapCell {
  user: string;
  day: number; // 0-6 (Sunday-Saturday)
  value: number;
  percentage: number; // Relative to max
}

/** Activity item for recent activity feed */
export interface ActivityItem {
  id: string;
  type: 'recording' | 'approval' | 'completion' | 'flagged' | 'returned';
  title: string;
  description: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  timestamp: string;
  metadata?: Record<string, unknown>;
}

/** Trend data point for charts */
export interface TrendDataPoint {
  date: string;
  label: string;
  recordings: number;
  minutes: number;
  approvals: number;
  completionRate: number;
}

/** Top performer entry */
export interface TopPerformer {
  userId: string;
  userName: string;
  userAvatar?: string;
  userRole: string;
  metric: number;
  metricLabel: string;
  rank: number;
  trend: 'up' | 'down' | 'stable';
  trendValue: number;
}

/** Leaderboard category */
export type LeaderboardCategory = 'completion' | 'turnaround' | 'volume';

/** Complete insights data structure */
export interface InsightsData {
  period: InsightPeriod;
  dateRange: { start: string; end: string };
  teamMetrics: TeamMetrics;
  userMetrics: UserMetrics[];
  sentimentTrend: SentimentTrend;
  workloadData: WorkloadData;
  trendData: TrendDataPoint[];
  recentActivity: ActivityItem[];
  topPerformers: {
    completion: TopPerformer[];
    turnaround: TopPerformer[];
    volume: TopPerformer[];
  };
}

/** Filter state for insights */
export interface InsightFilters {
  period: InsightPeriod;
  domain: string | null;
  team: string | null;
  userId: string | null;
}

/** Day name helper */
export const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

/** Day name full helper */
export const DAY_NAMES_FULL = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

/** Get period days */
export function getPeriodDays(period: InsightPeriod): number {
  const option = PERIOD_OPTIONS.find(p => p.value === period);
  return option?.days ?? 30;
}
