// This file is auto-generated by @hey-api/openapi-ts

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

/**
 * TranslationStatusEntry
 */
export type TranslationStatusEntry = {
  /**
   * Language
   */
  language: string
  status: JobStatus
  /**
   * Text
   */
  text?: string | null
  /**
   * Updated At
   */
  updated_at?: string | null
  /**
   * Error
   */
  error?: string | null
  /**
   * Requested By
   */
  requested_by?: string | null
  /**
   * Auto Requested
   */
  auto_requested?: boolean
}

/**
 * JobStatus
 */
export type JobStatus =
  | 'awaiting_start'
  | 'in_progress'
  | 'completed'
  | 'failed'

/**
 * TranslationRequest
 */
export type TranslationRequest = {
  /**
   * Languages
   */
  languages: Array<string>
  /**
   * Force
   */
  force?: boolean
}

/**
 * TranslationListResponse
 */
export type TranslationListResponse = {
  /**
   * Translations
   */
  translations: Array<TranslationStatusEntry>
}

/**
 * TranscriptionPatchRequest
 */
export type TranscriptionPatchRequest = {
  /**
   * Title
   */
  title?: string | null
  /**
   * Dialogue Entries
   */
  dialogue_entries?: Array<DialogueEntry> | null
  /**
   * Canonical Speaker
   */
  canonical_speaker?: string | null
}

/**
 * DialogueEntry
 */
export type DialogueEntry = {
  /**
   * Speaker
   */
  speaker: string
  /**
   * Text
   */
  text: string
  /**
   * Start Time
   */
  start_time: number
  /**
   * End Time
   */
  end_time: number
  /**
   * Canonical Speaker
   */
  canonical_speaker: string | null
}

/**
 * TranscriptionMetadata
 * Pydantic model for transcription metadata.
 */
export type TranscriptionMetadata = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Title
   */
  title?: string | null
  /**
   * Text
   */
  text: string
  status: JobStatus
  /**
   * Case Reference
   */
  case_reference?: string | null
  /**
   * Processing Mode
   */
  processing_mode?: string | null
  /**
   * Visit Type
   */
  visit_type?: string | null
  /**
   * Worker Team
   */
  worker_team?: string | null
}

/**
 * TranscriptionGetResponse
 */
export type TranscriptionGetResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Title
   */
  title: string | null
  /**
   * Dialogue Entries
   */
  dialogue_entries: Array<DialogueEntry> | null
  status: JobStatus
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Case Reference
   */
  case_reference?: string | null
  /**
   * Worker Team
   */
  worker_team?: string | null
  /**
   * Subject Initials
   */
  subject_initials?: string | null
  /**
   * Subject Dob
   */
  subject_dob?: string | null
  /**
   * Processing Mode
   */
  processing_mode?: string | null
}

/**
 * TranscriptionFeedbackRequest
 */
export type TranscriptionFeedbackRequest = {
  /**
   * Payload
   */
  payload: {
    [key: string]: unknown
  }
  /**
   * Wer
   */
  wer?: number | null
  /**
   * Der
   */
  der?: number | null
}

/**
 * TranscriptionDialogueUpdate
 */
export type TranscriptionDialogueUpdate = {
  /**
   * Dialogue Entries
   */
  dialogue_entries: Array<DialogueEntry>
}

/**
 * TranscriptionCreateResponse
 */
export type TranscriptionCreateResponse = {
  /**
   * Id
   */
  id: string
}

/**
 * TranscriptionCreateRequest
 */
export type TranscriptionCreateRequest = {
  /**
   * Recording Id
   */
  recording_id: string
  /**
   * Template Name
   */
  template_name: string
  /**
   * Template Id
   */
  template_id?: string | null
  /**
   * Agenda
   */
  agenda?: string | null
  /**
   * Title
   */
  title?: string | null
  /**
   * Case Reference
   */
  case_reference: string
  /**
   * Worker Team
   */
  worker_team?: string | null
  /**
   * Subject Initials
   */
  subject_initials?: string | null
  /**
   * Subject Dob
   */
  subject_dob?: string | null
  /**
   * Processing Mode
   * fast (realtime) or economy (batch/off-peak)
   */
  processing_mode?: string | null
  /**
   * Visit Type
   */
  visit_type?: string | null
  /**
   * Intended Outcomes
   */
  intended_outcomes?: string | null
  /**
   * Risk Flags
   */
  risk_flags?: string | null
}

/**
 * Transcription
 */
export type Transcription = {
  /**
   * Id
   */
  id?: string
  /**
   * Created Datetime
   */
  created_datetime?: string
  /**
   * Updated Datetime
   */
  updated_datetime?: string
  /**
   * Title
   */
  title?: string | null
  /**
   * Dialogue Entries
   */
  dialogue_entries?: Array<DialogueEntry> | null
  status?: JobStatus
  /**
   * Error
   */
  error?: string | null
  /**
   * User Id
   */
  user_id?: string | null
  /**
   * Organisation Id
   */
  organisation_id?: string | null
  /**
   * Service Domain Id
   */
  service_domain_id?: string | null
  /**
   * Case Id
   */
  case_id?: string | null
  /**
   * Case Reference
   */
  case_reference?: string | null
  /**
   * Worker Team
   */
  worker_team?: string | null
  /**
   * Subject Initials
   */
  subject_initials?: string | null
  /**
   * Subject Dob Ciphertext
   */
  subject_dob_ciphertext?: string | null
  /**
   * Visit Type
   */
  visit_type?: string | null
  /**
   * Intended Outcomes
   */
  intended_outcomes?: string | null
  /**
   * Risk Flags
   */
  risk_flags?: string | null
  /**
   * Docx Blob Path
   */
  docx_blob_path?: string | null
  /**
   * Pdf Blob Path
   */
  pdf_blob_path?: string | null
  /**
   * Sharepoint Docx Item Id
   */
  sharepoint_docx_item_id?: string | null
  /**
   * Sharepoint Pdf Item Id
   */
  sharepoint_pdf_item_id?: string | null
  /**
   * Planner Task Ids
   */
  planner_task_ids?: Array<string>
  export_status?: ExportStatus | null
  /**
   * Export Error
   */
  export_error?: string | null
  /**
   * Last Exported At
   */
  last_exported_at?: string | null
  /**
   * Processing Mode
   */
  processing_mode?: string
  /**
   * Legacy Minute Versions
   */
  legacy_minute_versions?: Array<{
    [key: string]: unknown
  }> | null
  /**
   * Translations
   * Map of language code to translation metadata
   */
  translations?: {
    [key: string]: unknown
  } | null
}

/**
 * ExportStatus
 */
export type ExportStatus =
  | 'awaiting_start'
  | 'in_progress'
  | 'completed'
  | 'failed'

/**
 * TenantConfig
 */
export type TenantConfig = {
  /**
   * Id
   * Stable tenant/council identifier
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Version
   * Config version tag, e.g. 1.0.0
   */
  version: string
  /**
   * Defaultlocale
   */
  defaultLocale: string
  /**
   * Designtokens
   */
  designTokens?: {
    [key: string]: unknown
  } | null
  /**
   * Retentiondaysdefault
   * Default retention in days for recordings/transcriptions/minutes
   */
  retentionDaysDefault?: number | null
  /**
   * Sharepoint Library Path
   * Default SharePoint library path
   */
  sharepoint_library_path?: string | null
  /**
   * Planner
   * Optional Planner plan/bucket ids
   */
  planner?: {
    [key: string]: unknown
  } | null
  /**
   * Language/translation configuration for the tenant
   */
  languages?: LanguageConfig | null
  /**
   * Modules
   */
  modules: Array<ModuleConfig>
}

/**
 * ModuleConfig
 */
export type ModuleConfig = {
  /**
   * Id
   * Module identifier, e.g. transcription, minutes
   */
  id: string
  /**
   * Enabled
   */
  enabled?: boolean
  /**
   * Label
   * Display label for navigation
   */
  label?: string | null
  /**
   * Icon
   * Optional icon name for navigation
   */
  icon?: string | null
  /**
   * Feature Flags
   * Optional feature flag identifiers required for this module
   */
  feature_flags?: Array<string> | null
  /**
   * Departments
   * Optional list of service_domain ids this module applies to
   */
  departments?: Array<string> | null
}

/**
 * LanguageConfig
 */
export type LanguageConfig = {
  /**
   * Default
   * Default language code (e.g. en)
   */
  default: string
  /**
   * Available
   * List of languages that can be requested
   */
  available?: Array<string>
  /**
   * Autotranslate
   * When true, automatically request translations after transcription completes
   */
  autoTranslate?: boolean
}

/**
 * TemplateType
 */
export type TemplateType = 'document' | 'form'

/**
 * TemplateResponse
 */
export type TemplateResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Name
   */
  name: string
  /**
   * Content
   */
  content: string
  /**
   * Description
   */
  description: string
  type: TemplateType
  /**
   * Questions
   */
  questions: Array<Question> | null
}

/**
 * Question
 */
export type Question = {
  /**
   * Position
   */
  position: number
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description: string
  /**
   * Id
   */
  id: string
}

/**
 * TemplateMetadata
 */
export type TemplateMetadata = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Category
   */
  category: string
  agenda_usage: AgendaUsage
  /**
   * Service Domains
   */
  service_domains?: Array<string> | null
}

/**
 * AgendaUsage
 */
export type AgendaUsage = 'not_used' | 'optional' | 'required'

/**
 * SingleRecordingSegment
 */
export type SingleRecordingSegment = {
  /**
   * Id
   */
  id: string
  /**
   * Url
   */
  url: string
  /**
   * Extension
   */
  extension: string
  /**
   * Start Seconds
   */
  start_seconds?: number | null
  /**
   * End Seconds
   */
  end_seconds?: number | null
}

/**
 * SingleRecording
 */
export type SingleRecording = {
  /**
   * Id
   */
  id: string
  /**
   * Url
   */
  url: string
  /**
   * Extension
   */
  extension: string
}

/**
 * RecordingCreateResponse
 */
export type RecordingCreateResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Upload Url
   */
  upload_url: string
}

/**
 * RecordingCreateRequest
 */
export type RecordingCreateRequest = {
  /**
   * File Extension
   */
  file_extension: string
  /**
   * Captured Offline
   */
  captured_offline?: boolean | null
}

/**
 * PatchUserTemplateRequest
 */
export type PatchUserTemplateRequest = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Content
   */
  content?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Questions
   */
  questions?: Array<CreateQuestion | Question> | null
}

/**
 * CreateQuestion
 */
export type CreateQuestion = {
  /**
   * Position
   */
  position: number
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description: string
}

/**
 * PaginatedTranscriptionsResponse
 * Paginated response for transcriptions.
 */
export type PaginatedTranscriptionsResponse = {
  /**
   * Items
   */
  items: Array<TranscriptionMetadata>
  /**
   * Total Count
   */
  total_count: number
  /**
   * Page
   */
  page: number
  /**
   * Page Size
   */
  page_size: number
  /**
   * Total Pages
   */
  total_pages: number
}

/**
 * MinutesCreateRequest
 */
export type MinutesCreateRequest = {
  /**
   * Template Name
   * Name of the template to use for the minutes
   */
  template_name: string
  /**
   * Template Id
   * Optional id of user template
   */
  template_id: string | null
  /**
   * Agenda
   * The agenda for the meeting
   */
  agenda?: string | null
  /**
   * Visit Type
   */
  visit_type?: string | null
  /**
   * Intended Outcomes
   */
  intended_outcomes?: string | null
  /**
   * Risk Flags
   */
  risk_flags?: string | null
}

/**
 * MinuteVersionResponse
 */
export type MinuteVersionResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Minute Id
   */
  minute_id: string
  status: JobStatus
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Html Content
   */
  html_content: string
  /**
   * Error
   */
  error: string | null
  /**
   * Ai Edit Instructions
   */
  ai_edit_instructions: string | null
  content_source: ContentSource
}

/**
 * ContentSource
 */
export type ContentSource = 'manual_edit' | 'ai_edit' | 'initial_generation'

/**
 * MinuteVersionCreateRequest
 */
export type MinuteVersionCreateRequest = {
  /**
   * If the content source is an AI edit, store the instruction and source version id here
   */
  ai_edit_instructions?: AiEdit | null
  content_source: ContentSource
  /**
   * Html Content
   */
  html_content?: string
}

/**
 * AiEdit
 */
export type AiEdit = {
  /**
   * Instruction
   */
  instruction: string
  /**
   * Source Id
   */
  source_id: string
}

/**
 * MinuteVersion
 */
export type MinuteVersion = {
  /**
   * Id
   */
  id?: string
  /**
   * Created Datetime
   */
  created_datetime?: string
  /**
   * Updated Datetime
   */
  updated_datetime?: string
  /**
   * Minute Id
   */
  minute_id: string
  /**
   * Html Content
   */
  html_content?: string
  status?: JobStatus
  /**
   * Error
   */
  error?: string | null
  /**
   * Ai Edit Instructions
   * If the content source is an AI edit, store the instruction here
   */
  ai_edit_instructions?: string | null
  content_source?: ContentSource
}

/**
 * MinuteListItem
 */
export type MinuteListItem = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Transcription Id
   */
  transcription_id: string
  /**
   * Template Name
   */
  template_name: string
  /**
   * Agenda
   */
  agenda: string | null
  /**
   * Case Reference
   */
  case_reference?: string | null
  /**
   * Visit Type
   */
  visit_type?: string | null
  /**
   * Intended Outcomes
   */
  intended_outcomes?: string | null
  /**
   * Risk Flags
   */
  risk_flags?: string | null
}

/**
 * Minute
 */
export type Minute = {
  /**
   * Id
   */
  id?: string
  /**
   * Created Datetime
   */
  created_datetime?: string
  /**
   * Updated Datetime
   */
  updated_datetime?: string
  /**
   * Transcription Id
   */
  transcription_id: string
  /**
   * Template Name
   */
  template_name?: string
  /**
   * User Template Id
   */
  user_template_id?: string | null
  /**
   * Created By User Id
   */
  created_by_user_id?: string | null
  /**
   * Agenda
   */
  agenda?: string | null
  /**
   * Organisation Id
   */
  organisation_id?: string | null
  /**
   * Service Domain Id
   */
  service_domain_id?: string | null
  /**
   * Case Id
   */
  case_id?: string | null
  /**
   * Case Reference
   */
  case_reference?: string | null
  /**
   * Worker Team
   */
  worker_team?: string | null
  /**
   * Subject Initials
   */
  subject_initials?: string | null
  /**
   * Subject Dob Ciphertext
   */
  subject_dob_ciphertext?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * GetUserResponse
 */
export type GetUserResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Email
   */
  email: string
  /**
   * Data Retention Days
   */
  data_retention_days: number | null
  /**
   * Strict Data Retention
   */
  strict_data_retention: boolean
}

/**
 * ExportResponse
 */
export type ExportResponse = {
  /**
   * Url
   */
  url: string
  /**
   * Format
   */
  format: string
  /**
   * Sharepoint Item Id
   */
  sharepoint_item_id?: string | null
  /**
   * Planner Task Ids
   */
  planner_task_ids?: Array<string> | null
}

/**
 * EvidenceClickRequest
 */
export type EvidenceClickRequest = {
  /**
   * Recording Id
   */
  recording_id: string
  /**
   * Start Time
   */
  start_time: number
  /**
   * End Time
   */
  end_time?: number | null
  /**
   * Citation Number
   */
  citation_number?: number | null
}

/**
 * DataRetentionUpdateResponse
 */
export type DataRetentionUpdateResponse = {
  /**
   * Data Retention Days
   */
  data_retention_days: number | null
}

/**
 * CreateUserTemplateRequest
 */
export type CreateUserTemplateRequest = {
  /**
   * Name
   */
  name: string
  /**
   * Content
   */
  content: string
  /**
   * Description
   */
  description: string
  type: TemplateType
  /**
   * Questions
   */
  questions?: Array<CreateQuestion> | null
}

/**
 * ConfigVersionItem
 */
export type ConfigVersionItem = {
  /**
   * Version
   */
  version: string
  /**
   * Timestamp
   */
  timestamp: string
  /**
   * Author
   */
  author: string
  /**
   * Changes
   */
  changes: Array<string>
}

/**
 * ConfigListResponse
 */
export type ConfigListResponse = {
  /**
   * Configs
   */
  configs: Array<ConfigListItem>
}

/**
 * ConfigListItem
 */
export type ConfigListItem = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Version
   */
  version: string
  /**
   * Lastmodified
   */
  lastModified: string
}

/**
 * ConfigHistoryResponse
 */
export type ConfigHistoryResponse = {
  /**
   * Configname
   */
  configName: string
  /**
   * Versions
   */
  versions: Array<ConfigVersionItem>
}

/**
 * ConfigAuditResponse
 */
export type ConfigAuditResponse = {
  /**
   * Entries
   */
  entries: Array<AuditEntryResponse>
}

/**
 * AuditEntryResponse
 */
export type AuditEntryResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Timestamp
   */
  timestamp: string
  /**
   * User
   */
  user: string
  /**
   * Action
   */
  action: string
  /**
   * Outcome
   */
  outcome: string
}

/**
 * ChatGetResponse
 */
export type ChatGetResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * User Content
   */
  user_content: string
  /**
   * Assistant Content
   */
  assistant_content: string | null
  status: JobStatus
}

/**
 * ChatGetAllResponse
 */
export type ChatGetAllResponse = {
  /**
   * Chat
   */
  chat: Array<ChatGetResponse>
}

/**
 * ChatCreateResponse
 */
export type ChatCreateResponse = {
  /**
   * Id
   */
  id: string
}

/**
 * ChatCreateRequest
 */
export type ChatCreateRequest = {
  /**
   * User Content
   */
  user_content: string
}

/**
 * AccessCheckResponse
 */
export type AccessCheckResponse = {
  /**
   * Hasaccess
   */
  hasAccess: boolean
  /**
   * Role
   */
  role?: string | null
}

export type ListTranscriptionsTranscriptionsGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: {
    /**
     * Page
     * Page number (starts from 1)
     */
    page?: number
    /**
     * Page Size
     * Number of items per page
     */
    page_size?: number
  }
  url: '/transcriptions'
}

export type ListTranscriptionsTranscriptionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListTranscriptionsTranscriptionsGetError =
  ListTranscriptionsTranscriptionsGetErrors[keyof ListTranscriptionsTranscriptionsGetErrors]

export type ListTranscriptionsTranscriptionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedTranscriptionsResponse
}

export type ListTranscriptionsTranscriptionsGetResponse =
  ListTranscriptionsTranscriptionsGetResponses[keyof ListTranscriptionsTranscriptionsGetResponses]

export type CreateTranscriptionTranscriptionsPostData = {
  body: TranscriptionCreateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/transcriptions'
}

export type CreateTranscriptionTranscriptionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateTranscriptionTranscriptionsPostError =
  CreateTranscriptionTranscriptionsPostErrors[keyof CreateTranscriptionTranscriptionsPostErrors]

export type CreateTranscriptionTranscriptionsPostResponses = {
  /**
   * Successful Response
   */
  201: TranscriptionCreateResponse
}

export type CreateTranscriptionTranscriptionsPostResponse =
  CreateTranscriptionTranscriptionsPostResponses[keyof CreateTranscriptionTranscriptionsPostResponses]

export type CreateRecordingRecordingsPostData = {
  body: RecordingCreateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/recordings'
}

export type CreateRecordingRecordingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateRecordingRecordingsPostError =
  CreateRecordingRecordingsPostErrors[keyof CreateRecordingRecordingsPostErrors]

export type CreateRecordingRecordingsPostResponses = {
  /**
   * Successful Response
   */
  200: RecordingCreateResponse
}

export type CreateRecordingRecordingsPostResponse =
  CreateRecordingRecordingsPostResponses[keyof CreateRecordingRecordingsPostResponses]

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}'
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError =
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors[keyof DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors]

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse =
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses[keyof DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses]

export type GetTranscriptionTranscriptionsTranscriptionIdGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}'
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetError =
  GetTranscriptionTranscriptionsTranscriptionIdGetErrors[keyof GetTranscriptionTranscriptionsTranscriptionIdGetErrors]

export type GetTranscriptionTranscriptionsTranscriptionIdGetResponses = {
  /**
   * Successful Response
   */
  200: TranscriptionGetResponse
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetResponse =
  GetTranscriptionTranscriptionsTranscriptionIdGetResponses[keyof GetTranscriptionTranscriptionsTranscriptionIdGetResponses]

export type SaveTranscriptionTranscriptionsTranscriptionIdPatchData = {
  body: TranscriptionPatchRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}'
}

export type SaveTranscriptionTranscriptionsTranscriptionIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SaveTranscriptionTranscriptionsTranscriptionIdPatchError =
  SaveTranscriptionTranscriptionsTranscriptionIdPatchErrors[keyof SaveTranscriptionTranscriptionsTranscriptionIdPatchErrors]

export type SaveTranscriptionTranscriptionsTranscriptionIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Transcription
}

export type SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse =
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponses[keyof SaveTranscriptionTranscriptionsTranscriptionIdPatchResponses]

export type GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData =
  {
    body?: never
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/translations'
  }

export type GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetError =
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetErrors[keyof GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetErrors]

export type GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponses =
  {
    /**
     * Successful Response
     */
    200: TranslationListResponse
  }

export type GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponse =
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponses[keyof GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetResponses]

export type RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData =
  {
    body: TranslationRequest
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/translate'
  }

export type RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostError =
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostErrors[keyof RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostErrors]

export type RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponses =
  {
    /**
     * Successful Response
     */
    200: TranslationListResponse
  }

export type RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponse =
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponses[keyof RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponses]

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData =
  {
    body?: never
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/recordings'
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError =
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors[keyof GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors]

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses =
  {
    /**
     * Response Get Recordings For Transcription Transcriptions  Transcription Id  Recordings Get
     * Successful Response
     */
    200: Array<SingleRecording>
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse =
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses[keyof GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses]

export type GetSignedRecordingRecordingsRecordingIdSignedUrlGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Recording Id
     */
    recording_id: string
  }
  query?: never
  url: '/recordings/{recording_id}/signed-url'
}

export type GetSignedRecordingRecordingsRecordingIdSignedUrlGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSignedRecordingRecordingsRecordingIdSignedUrlGetError =
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetErrors[keyof GetSignedRecordingRecordingsRecordingIdSignedUrlGetErrors]

export type GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponses = {
  /**
   * Successful Response
   */
  200: SingleRecording
}

export type GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponse =
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponses[keyof GetSignedRecordingRecordingsRecordingIdSignedUrlGetResponses]

export type GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData =
  {
    body?: never
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
      /**
       * Recording Id
       */
      recording_id: string
    }
    query?: {
      /**
       * Start Seconds
       */
      start_seconds?: number
      /**
       * End Seconds
       */
      end_seconds?: number | null
    }
    url: '/transcriptions/{transcription_id}/recordings/{recording_id}/signed-url-range'
  }

export type GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetError =
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetErrors[keyof GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetErrors]

export type GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponses =
  {
    /**
     * Successful Response
     */
    200: SingleRecordingSegment
  }

export type GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponse =
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponses[keyof GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetResponses]

export type RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData =
  {
    body: EvidenceClickRequest
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/evidence-click'
  }

export type RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostError =
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostErrors[keyof RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostErrors]

export type RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponse =
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponses[keyof RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponses]

export type GetDialogueTranscriptionsTranscriptionIdDialogueGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/dialogue'
}

export type GetDialogueTranscriptionsTranscriptionIdDialogueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetDialogueTranscriptionsTranscriptionIdDialogueGetError =
  GetDialogueTranscriptionsTranscriptionIdDialogueGetErrors[keyof GetDialogueTranscriptionsTranscriptionIdDialogueGetErrors]

export type GetDialogueTranscriptionsTranscriptionIdDialogueGetResponses = {
  /**
   * Response Get Dialogue Transcriptions  Transcription Id  Dialogue Get
   * Successful Response
   */
  200: Array<DialogueEntry>
}

export type GetDialogueTranscriptionsTranscriptionIdDialogueGetResponse =
  GetDialogueTranscriptionsTranscriptionIdDialogueGetResponses[keyof GetDialogueTranscriptionsTranscriptionIdDialogueGetResponses]

export type UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData = {
  body: TranscriptionDialogueUpdate
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/dialogue'
}

export type UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchError =
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchErrors[keyof UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchErrors]

export type UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponses =
  {
    /**
     * Response Update Dialogue Transcriptions  Transcription Id  Dialogue Patch
     * Successful Response
     */
    200: Array<DialogueEntry>
  }

export type UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponse =
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponses[keyof UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponses]

export type SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData = {
  body: TranscriptionFeedbackRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/feedback'
}

export type SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostError =
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostErrors[keyof SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostErrors]

export type SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponse =
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponses[keyof SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponses]

export type GetUserUsersMeGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/users/me'
}

export type GetUserUsersMeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserUsersMeGetError =
  GetUserUsersMeGetErrors[keyof GetUserUsersMeGetErrors]

export type GetUserUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type GetUserUsersMeGetResponse =
  GetUserUsersMeGetResponses[keyof GetUserUsersMeGetResponses]

export type UpdateDataRetentionUsersDataRetentionPatchData = {
  body: DataRetentionUpdateResponse
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/users/data-retention'
}

export type UpdateDataRetentionUsersDataRetentionPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateDataRetentionUsersDataRetentionPatchError =
  UpdateDataRetentionUsersDataRetentionPatchErrors[keyof UpdateDataRetentionUsersDataRetentionPatchErrors]

export type UpdateDataRetentionUsersDataRetentionPatchResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type UpdateDataRetentionUsersDataRetentionPatchResponse =
  UpdateDataRetentionUsersDataRetentionPatchResponses[keyof UpdateDataRetentionUsersDataRetentionPatchResponses]

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData =
  {
    body?: never
    headers?: {
      /**
       * Authorization
       */
      authorization?: string | null
      /**
       * X-Amzn-Oidc-Accesstoken
       */
      'x-amzn-oidc-accesstoken'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcription/{transcription_id}/minutes'
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError =
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors[keyof ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors]

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses =
  {
    /**
     * Response List Minutes For Transcription Transcription  Transcription Id  Minutes Get
     * Successful Response
     */
    200: Array<MinuteListItem>
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse =
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses[keyof ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses]

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostData = {
  body: MinutesCreateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcription/{transcription_id}/minutes'
}

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostError =
  CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors[keyof CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors]

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetMinuteMinutesMinutesIdGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minutes Id
     */
    minutes_id: string
  }
  query?: never
  url: '/minutes/{minutes_id}'
}

export type GetMinuteMinutesMinutesIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetMinuteMinutesMinutesIdGetError =
  GetMinuteMinutesMinutesIdGetErrors[keyof GetMinuteMinutesMinutesIdGetErrors]

export type GetMinuteMinutesMinutesIdGetResponses = {
  /**
   * Successful Response
   */
  200: Minute
}

export type GetMinuteMinutesMinutesIdGetResponse =
  GetMinuteMinutesMinutesIdGetResponses[keyof GetMinuteMinutesMinutesIdGetResponses]

export type ListMinuteVersionsMinutesMinuteIdVersionsGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minute Id
     */
    minute_id: string
  }
  query?: never
  url: '/minutes/{minute_id}/versions'
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetError =
  ListMinuteVersionsMinutesMinuteIdVersionsGetErrors[keyof ListMinuteVersionsMinutesMinuteIdVersionsGetErrors]

export type ListMinuteVersionsMinutesMinuteIdVersionsGetResponses = {
  /**
   * Response List Minute Versions Minutes  Minute Id  Versions Get
   * Successful Response
   */
  200: Array<MinuteVersionResponse>
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetResponse =
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponses[keyof ListMinuteVersionsMinutesMinuteIdVersionsGetResponses]

export type CreateMinuteVersionMinutesMinuteIdVersionsPostData = {
  body: MinuteVersionCreateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minute Id
     */
    minute_id: string
  }
  query?: never
  url: '/minutes/{minute_id}/versions'
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostError =
  CreateMinuteVersionMinutesMinuteIdVersionsPostErrors[keyof CreateMinuteVersionMinutesMinuteIdVersionsPostErrors]

export type CreateMinuteVersionMinutesMinuteIdVersionsPostResponses = {
  /**
   * Successful Response
   */
  200: MinuteVersionResponse
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostResponse =
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponses[keyof CreateMinuteVersionMinutesMinuteIdVersionsPostResponses]

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minute Version Id
     */
    minute_version_id: string
  }
  query?: never
  url: '/minute_versions/{minute_version_id}'
}

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError =
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors[keyof DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors]

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minute Version Id
     */
    minute_version_id: string
  }
  query?: never
  url: '/minute_versions/{minute_version_id}'
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetError =
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors[keyof GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors]

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses = {
  /**
   * Successful Response
   */
  200: MinuteVersion
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse =
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses[keyof GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses]

export type ExportMinuteMinutesMinuteIdExportPostData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Minute Id
     */
    minute_id: string
  }
  query?: {
    /**
     * Format
     */
    format?: string
  }
  url: '/minutes/{minute_id}/export'
}

export type ExportMinuteMinutesMinuteIdExportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ExportMinuteMinutesMinuteIdExportPostError =
  ExportMinuteMinutesMinuteIdExportPostErrors[keyof ExportMinuteMinutesMinuteIdExportPostErrors]

export type ExportMinuteMinutesMinuteIdExportPostResponses = {
  /**
   * Successful Response
   */
  200: ExportResponse
}

export type ExportMinuteMinutesMinuteIdExportPostResponse =
  ExportMinuteMinutesMinuteIdExportPostResponses[keyof ExportMinuteMinutesMinuteIdExportPostResponses]

export type GetTemplatesTemplatesGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/templates'
}

export type GetTemplatesTemplatesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTemplatesTemplatesGetError =
  GetTemplatesTemplatesGetErrors[keyof GetTemplatesTemplatesGetErrors]

export type GetTemplatesTemplatesGetResponses = {
  /**
   * Response Get Templates Templates Get
   * Successful Response
   */
  200: Array<TemplateMetadata>
}

export type GetTemplatesTemplatesGetResponse =
  GetTemplatesTemplatesGetResponses[keyof GetTemplatesTemplatesGetResponses]

export type GetUserTemplatesUserTemplatesGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/user-templates'
}

export type GetUserTemplatesUserTemplatesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserTemplatesUserTemplatesGetError =
  GetUserTemplatesUserTemplatesGetErrors[keyof GetUserTemplatesUserTemplatesGetErrors]

export type GetUserTemplatesUserTemplatesGetResponses = {
  /**
   * Response Get User Templates User Templates Get
   * Successful Response
   */
  200: Array<TemplateResponse>
}

export type GetUserTemplatesUserTemplatesGetResponse =
  GetUserTemplatesUserTemplatesGetResponses[keyof GetUserTemplatesUserTemplatesGetResponses]

export type CreateUserTemplateUserTemplatesPostData = {
  body: CreateUserTemplateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path?: never
  query?: never
  url: '/user-templates'
}

export type CreateUserTemplateUserTemplatesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateUserTemplateUserTemplatesPostError =
  CreateUserTemplateUserTemplatesPostErrors[keyof CreateUserTemplateUserTemplatesPostErrors]

export type CreateUserTemplateUserTemplatesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteError =
  DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors[keyof DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors]

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetUserTemplateUserTemplatesTemplateIdGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type GetUserTemplateUserTemplatesTemplateIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserTemplateUserTemplatesTemplateIdGetError =
  GetUserTemplateUserTemplatesTemplateIdGetErrors[keyof GetUserTemplateUserTemplatesTemplateIdGetErrors]

export type GetUserTemplateUserTemplatesTemplateIdGetResponses = {
  /**
   * Successful Response
   */
  200: TemplateResponse
}

export type GetUserTemplateUserTemplatesTemplateIdGetResponse =
  GetUserTemplateUserTemplatesTemplateIdGetResponses[keyof GetUserTemplateUserTemplatesTemplateIdGetResponses]

export type EditUserTemplateUserTemplatesTemplateIdPatchData = {
  body: PatchUserTemplateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type EditUserTemplateUserTemplatesTemplateIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type EditUserTemplateUserTemplatesTemplateIdPatchError =
  EditUserTemplateUserTemplatesTemplateIdPatchErrors[keyof EditUserTemplateUserTemplatesTemplateIdPatchErrors]

export type EditUserTemplateUserTemplatesTemplateIdPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}/duplicate'
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError =
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors[keyof DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors]

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown
  }

export type GetTenantConfigConfigTenantIdGetData = {
  body?: never
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string
  }
  query?: never
  url: '/config/{tenant_id}'
}

export type GetTenantConfigConfigTenantIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTenantConfigConfigTenantIdGetError =
  GetTenantConfigConfigTenantIdGetErrors[keyof GetTenantConfigConfigTenantIdGetErrors]

export type GetTenantConfigConfigTenantIdGetResponses = {
  /**
   * Successful Response
   */
  200: TenantConfig
}

export type GetTenantConfigConfigTenantIdGetResponse =
  GetTenantConfigConfigTenantIdGetResponses[keyof GetTenantConfigConfigTenantIdGetResponses]

export type CheckAdminAccessAdminCheckAccessGetData = {
  body?: never
  path?: never
  query: {
    /**
     * Args
     */
    args: unknown
    /**
     * Kwargs
     */
    kwargs: unknown
  }
  url: '/admin/check-access'
}

export type CheckAdminAccessAdminCheckAccessGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CheckAdminAccessAdminCheckAccessGetError =
  CheckAdminAccessAdminCheckAccessGetErrors[keyof CheckAdminAccessAdminCheckAccessGetErrors]

export type CheckAdminAccessAdminCheckAccessGetResponses = {
  /**
   * Successful Response
   */
  200: AccessCheckResponse
}

export type CheckAdminAccessAdminCheckAccessGetResponse =
  CheckAdminAccessAdminCheckAccessGetResponses[keyof CheckAdminAccessAdminCheckAccessGetResponses]

export type ListConfigsAdminConfigsGetData = {
  body?: never
  path?: never
  query: {
    /**
     * Args
     */
    args: unknown
    /**
     * Kwargs
     */
    kwargs: unknown
  }
  url: '/admin/configs'
}

export type ListConfigsAdminConfigsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListConfigsAdminConfigsGetError =
  ListConfigsAdminConfigsGetErrors[keyof ListConfigsAdminConfigsGetErrors]

export type ListConfigsAdminConfigsGetResponses = {
  /**
   * Successful Response
   */
  200: ConfigListResponse
}

export type ListConfigsAdminConfigsGetResponse =
  ListConfigsAdminConfigsGetResponses[keyof ListConfigsAdminConfigsGetResponses]

export type GetConfigDetailAdminConfigsTenantIdGetData = {
  body?: never
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string
  }
  query: {
    /**
     * Args
     */
    args: unknown
    /**
     * Kwargs
     */
    kwargs: unknown
  }
  url: '/admin/configs/{tenant_id}'
}

export type GetConfigDetailAdminConfigsTenantIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetConfigDetailAdminConfigsTenantIdGetError =
  GetConfigDetailAdminConfigsTenantIdGetErrors[keyof GetConfigDetailAdminConfigsTenantIdGetErrors]

export type GetConfigDetailAdminConfigsTenantIdGetResponses = {
  /**
   * Successful Response
   */
  200: TenantConfig
}

export type GetConfigDetailAdminConfigsTenantIdGetResponse =
  GetConfigDetailAdminConfigsTenantIdGetResponses[keyof GetConfigDetailAdminConfigsTenantIdGetResponses]

export type GetConfigAuditAdminConfigsTenantIdAuditGetData = {
  body?: never
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string
  }
  query: {
    /**
     * Args
     */
    args: unknown
    /**
     * Kwargs
     */
    kwargs: unknown
  }
  url: '/admin/configs/{tenant_id}/audit'
}

export type GetConfigAuditAdminConfigsTenantIdAuditGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetConfigAuditAdminConfigsTenantIdAuditGetError =
  GetConfigAuditAdminConfigsTenantIdAuditGetErrors[keyof GetConfigAuditAdminConfigsTenantIdAuditGetErrors]

export type GetConfigAuditAdminConfigsTenantIdAuditGetResponses = {
  /**
   * Successful Response
   */
  200: ConfigAuditResponse
}

export type GetConfigAuditAdminConfigsTenantIdAuditGetResponse =
  GetConfigAuditAdminConfigsTenantIdAuditGetResponses[keyof GetConfigAuditAdminConfigsTenantIdAuditGetResponses]

export type GetConfigHistoryAdminConfigsTenantIdHistoryGetData = {
  body?: never
  path: {
    /**
     * Tenant Id
     */
    tenant_id: string
  }
  query: {
    /**
     * Args
     */
    args: unknown
    /**
     * Kwargs
     */
    kwargs: unknown
  }
  url: '/admin/configs/{tenant_id}/history'
}

export type GetConfigHistoryAdminConfigsTenantIdHistoryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetConfigHistoryAdminConfigsTenantIdHistoryGetError =
  GetConfigHistoryAdminConfigsTenantIdHistoryGetErrors[keyof GetConfigHistoryAdminConfigsTenantIdHistoryGetErrors]

export type GetConfigHistoryAdminConfigsTenantIdHistoryGetResponses = {
  /**
   * Successful Response
   */
  200: ConfigHistoryResponse
}

export type GetConfigHistoryAdminConfigsTenantIdHistoryGetResponse =
  GetConfigHistoryAdminConfigsTenantIdHistoryGetResponses[keyof GetConfigHistoryAdminConfigsTenantIdHistoryGetResponses]

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteError =
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors[keyof DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors]

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse =
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses[keyof DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses]

export type ListChatTranscriptionsTranscriptionIdChatGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type ListChatTranscriptionsTranscriptionIdChatGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatTranscriptionsTranscriptionIdChatGetError =
  ListChatTranscriptionsTranscriptionIdChatGetErrors[keyof ListChatTranscriptionsTranscriptionIdChatGetErrors]

export type ListChatTranscriptionsTranscriptionIdChatGetResponses = {
  /**
   * Successful Response
   */
  200: ChatGetAllResponse
}

export type ListChatTranscriptionsTranscriptionIdChatGetResponse =
  ListChatTranscriptionsTranscriptionIdChatGetResponses[keyof ListChatTranscriptionsTranscriptionIdChatGetResponses]

export type CreateChatTranscriptionsTranscriptionIdChatPostData = {
  body: ChatCreateRequest
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type CreateChatTranscriptionsTranscriptionIdChatPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateChatTranscriptionsTranscriptionIdChatPostError =
  CreateChatTranscriptionsTranscriptionIdChatPostErrors[keyof CreateChatTranscriptionsTranscriptionIdChatPostErrors]

export type CreateChatTranscriptionsTranscriptionIdChatPostResponses = {
  /**
   * Successful Response
   */
  201: ChatCreateResponse
}

export type CreateChatTranscriptionsTranscriptionIdChatPostResponse =
  CreateChatTranscriptionsTranscriptionIdChatPostResponses[keyof CreateChatTranscriptionsTranscriptionIdChatPostResponses]

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat/{chat_id}'
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError =
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors[keyof DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors]

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse =
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses[keyof DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses]

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null
    /**
     * X-Amzn-Oidc-Accesstoken
     */
    'x-amzn-oidc-accesstoken'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat/{chat_id}'
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetError =
  GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors[keyof GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors]

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses = {
  /**
   * Successful Response
   */
  200: ChatGetResponse
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse =
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses[keyof GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses]

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}
