// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  listTranscriptionsTranscriptionsGet,
  createTranscriptionTranscriptionsPost,
  createRecordingRecordingsPost,
  deleteTranscriptionTranscriptionsTranscriptionIdDelete,
  getTranscriptionTranscriptionsTranscriptionIdGet,
  saveTranscriptionTranscriptionsTranscriptionIdPatch,
  getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGet,
  requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePost,
  getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet,
  getSignedRecordingRecordingsRecordingIdSignedUrlGet,
  getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGet,
  recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPost,
  getDialogueTranscriptionsTranscriptionIdDialogueGet,
  updateDialogueTranscriptionsTranscriptionIdDialoguePatch,
  submitFeedbackTranscriptionsTranscriptionIdFeedbackPost,
  getUserUsersMeGet,
  updateDataRetentionUsersDataRetentionPatch,
  listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet,
  createMinuteTranscriptionTranscriptionIdMinutesPost,
  getMinuteMinutesMinutesIdGet,
  listMinuteVersionsMinutesMinuteIdVersionsGet,
  createMinuteVersionMinutesMinuteIdVersionsPost,
  deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete,
  getMinuteVersionMinuteVersionsMinuteVersionIdGet,
  listMinuteTasksMinutesMinuteIdTasksGet,
  createMinuteTaskMinutesMinuteIdTasksPost,
  patchMinuteTaskMinutesMinuteIdTasksTaskIdPatch,
  pushMinuteTasksMinutesMinuteIdTasksPushPost,
  exportMinuteMinutesMinuteIdExportPost,
  getTemplatesTemplatesGet,
  getUserTemplatesUserTemplatesGet,
  createUserTemplateUserTemplatesPost,
  deleteUserTemplateUserTemplatesTemplateIdDelete,
  getUserTemplateUserTemplatesTemplateIdGet,
  editUserTemplateUserTemplatesTemplateIdPatch,
  duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost,
  getTenantConfigConfigTenantIdGet,
  getUserModulesModulesGet,
  checkAdminAccessAdminCheckAccessGet,
  listConfigsAdminConfigsGet,
  getConfigDetailAdminConfigsTenantIdGet,
  getConfigAuditAdminConfigsTenantIdAuditGet,
  getConfigHistoryAdminConfigsTenantIdHistoryGet,
  listMyTasksTasksGet,
  deleteChatsTranscriptionsTranscriptionIdChatDelete,
  listChatTranscriptionsTranscriptionIdChatGet,
  createChatTranscriptionsTranscriptionIdChatPost,
  deleteChatTranscriptionsTranscriptionIdChatChatIdDelete,
  getChatTranscriptionsTranscriptionIdChatChatIdGet,
} from '../sdk.gen'
import {
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
  type UseMutationOptions,
} from '@tanstack/react-query'
import type {
  ListTranscriptionsTranscriptionsGetData,
  ListTranscriptionsTranscriptionsGetError,
  ListTranscriptionsTranscriptionsGetResponse,
  CreateTranscriptionTranscriptionsPostData,
  CreateTranscriptionTranscriptionsPostError,
  CreateTranscriptionTranscriptionsPostResponse,
  CreateRecordingRecordingsPostData,
  CreateRecordingRecordingsPostError,
  CreateRecordingRecordingsPostResponse,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  GetTranscriptionTranscriptionsTranscriptionIdGetData,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchData,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
  GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostError,
  RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponse,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
  GetSignedRecordingRecordingsRecordingIdSignedUrlGetData,
  GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostError,
  RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponse,
  GetDialogueTranscriptionsTranscriptionIdDialogueGetData,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchError,
  UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponse,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostError,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponse,
  GetUserUsersMeGetData,
  UpdateDataRetentionUsersDataRetentionPatchData,
  UpdateDataRetentionUsersDataRetentionPatchError,
  UpdateDataRetentionUsersDataRetentionPatchResponse,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  GetMinuteMinutesMinutesIdGetData,
  ListMinuteVersionsMinutesMinuteIdVersionsGetData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
  ListMinuteTasksMinutesMinuteIdTasksGetData,
  CreateMinuteTaskMinutesMinuteIdTasksPostData,
  CreateMinuteTaskMinutesMinuteIdTasksPostError,
  CreateMinuteTaskMinutesMinuteIdTasksPostResponse,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchError,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchResponse,
  PushMinuteTasksMinutesMinuteIdTasksPushPostData,
  PushMinuteTasksMinutesMinuteIdTasksPushPostError,
  PushMinuteTasksMinutesMinuteIdTasksPushPostResponse,
  ExportMinuteMinutesMinuteIdExportPostData,
  ExportMinuteMinutesMinuteIdExportPostError,
  ExportMinuteMinutesMinuteIdExportPostResponse,
  GetTemplatesTemplatesGetData,
  GetUserTemplatesUserTemplatesGetData,
  CreateUserTemplateUserTemplatesPostData,
  CreateUserTemplateUserTemplatesPostError,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  GetUserTemplateUserTemplatesTemplateIdGetData,
  EditUserTemplateUserTemplatesTemplateIdPatchData,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
  GetTenantConfigConfigTenantIdGetData,
  GetUserModulesModulesGetData,
  CheckAdminAccessAdminCheckAccessGetData,
  ListConfigsAdminConfigsGetData,
  GetConfigDetailAdminConfigsTenantIdGetData,
  GetConfigAuditAdminConfigsTenantIdAuditGetData,
  GetConfigHistoryAdminConfigsTenantIdHistoryGetData,
  ListMyTasksTasksGetData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  ListChatTranscriptionsTranscriptionIdChatGetData,
  CreateChatTranscriptionsTranscriptionIdChatPostData,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
} from '../types.gen'
import { client as _heyApiClient } from '../client.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listTranscriptionsTranscriptionsGetQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) => createQueryKey('listTranscriptionsTranscriptionsGet', options)

/**
 * List Transcriptions
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTranscriptionsTranscriptionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listTranscriptionsTranscriptionsGetQueryKey(options),
  })
}

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {
    ...queryKey[0],
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listTranscriptionsTranscriptionsGetInfiniteQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
): QueryKey<Options<ListTranscriptionsTranscriptionsGetData>> =>
  createQueryKey('listTranscriptionsTranscriptionsGet', options, true)

/**
 * List Transcriptions
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetInfiniteOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) => {
  return infiniteQueryOptions<
    ListTranscriptionsTranscriptionsGetResponse,
    ListTranscriptionsTranscriptionsGetError,
    InfiniteData<ListTranscriptionsTranscriptionsGetResponse>,
    QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listTranscriptionsTranscriptionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listTranscriptionsTranscriptionsGetInfiniteQueryKey(options),
    }
  )
}

export const createTranscriptionTranscriptionsPostQueryKey = (
  options: Options<CreateTranscriptionTranscriptionsPostData>
) => createQueryKey('createTranscriptionTranscriptionsPost', options)

/**
 * Create Transcription
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPostOptions = (
  options: Options<CreateTranscriptionTranscriptionsPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createTranscriptionTranscriptionsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createTranscriptionTranscriptionsPostQueryKey(options),
  })
}

/**
 * Create Transcription
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPostMutation = (
  options?: Partial<Options<CreateTranscriptionTranscriptionsPostData>>
): UseMutationOptions<
  CreateTranscriptionTranscriptionsPostResponse,
  CreateTranscriptionTranscriptionsPostError,
  Options<CreateTranscriptionTranscriptionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTranscriptionTranscriptionsPostResponse,
    CreateTranscriptionTranscriptionsPostError,
    Options<CreateTranscriptionTranscriptionsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createTranscriptionTranscriptionsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const createRecordingRecordingsPostQueryKey = (
  options: Options<CreateRecordingRecordingsPostData>
) => createQueryKey('createRecordingRecordingsPost', options)

/**
 * Create Recording
 */
export const createRecordingRecordingsPostOptions = (
  options: Options<CreateRecordingRecordingsPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createRecordingRecordingsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createRecordingRecordingsPostQueryKey(options),
  })
}

/**
 * Create Recording
 */
export const createRecordingRecordingsPostMutation = (
  options?: Partial<Options<CreateRecordingRecordingsPostData>>
): UseMutationOptions<
  CreateRecordingRecordingsPostResponse,
  CreateRecordingRecordingsPostError,
  Options<CreateRecordingRecordingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRecordingRecordingsPostResponse,
    CreateRecordingRecordingsPostError,
    Options<CreateRecordingRecordingsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createRecordingRecordingsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Transcription
 * Delete a specific transcription by ID.
 */
export const deleteTranscriptionTranscriptionsTranscriptionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  >
): UseMutationOptions<
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await deleteTranscriptionTranscriptionsTranscriptionIdDelete({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getTranscriptionTranscriptionsTranscriptionIdGetQueryKey = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) => createQueryKey('getTranscriptionTranscriptionsTranscriptionIdGet', options)

/**
 * Get Transcription
 * Get a specific transcription by ID.
 */
export const getTranscriptionTranscriptionsTranscriptionIdGetOptions = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTranscriptionTranscriptionsTranscriptionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTranscriptionTranscriptionsTranscriptionIdGetQueryKey(options),
  })
}

/**
 * Save Transcription
 * Save or update a transcription.
 */
export const saveTranscriptionTranscriptionsTranscriptionIdPatchMutation = (
  options?: Partial<
    Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
  >
): UseMutationOptions<
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
  Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
    SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
    Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await saveTranscriptionTranscriptionsTranscriptionIdPatch({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetQueryKey =
  (
    options: Options<GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData>
  ) =>
    createQueryKey(
      'getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGet',
      options
    )

/**
 * Get Transcription Translations
 */
export const getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetOptions =
  (
    options: Options<GetTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        getTranscriptionTranslationsTranscriptionsTranscriptionIdTranslationsGetQueryKey(
          options
        ),
    })
  }

export const requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostQueryKey =
  (
    options: Options<RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData>
  ) =>
    createQueryKey(
      'requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePost',
      options
    )

/**
 * Request Transcription Translation
 */
export const requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostOptions =
  (
    options: Options<RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePost(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostQueryKey(
          options
        ),
    })
  }

/**
 * Request Transcription Translation
 */
export const requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostMutation =
  (
    options?: Partial<
      Options<RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData>
    >
  ): UseMutationOptions<
    RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponse,
    RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostError,
    Options<RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData>
  > => {
    const mutationOptions: UseMutationOptions<
      RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostResponse,
      RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostError,
      Options<RequestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePostData>
    > = {
      mutationFn: async (localOptions) => {
        const { data } =
          await requestTranscriptionTranslationTranscriptionsTranscriptionIdTranslatePost(
            {
              ...options,
              ...localOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) =>
    createQueryKey(
      'getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet',
      options
    )

/**
 * Get Recordings For Transcription
 */
export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetOptions =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey(
          options
        ),
    })
  }

export const getSignedRecordingRecordingsRecordingIdSignedUrlGetQueryKey = (
  options: Options<GetSignedRecordingRecordingsRecordingIdSignedUrlGetData>
) =>
  createQueryKey('getSignedRecordingRecordingsRecordingIdSignedUrlGet', options)

/**
 * Get Signed Recording
 */
export const getSignedRecordingRecordingsRecordingIdSignedUrlGetOptions = (
  options: Options<GetSignedRecordingRecordingsRecordingIdSignedUrlGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await getSignedRecordingRecordingsRecordingIdSignedUrlGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        })
      return data
    },
    queryKey:
      getSignedRecordingRecordingsRecordingIdSignedUrlGetQueryKey(options),
  })
}

export const getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetQueryKey =
  (
    options: Options<GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData>
  ) =>
    createQueryKey(
      'getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGet',
      options
    )

/**
 * Get Signed Recording Range
 */
export const getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetOptions =
  (
    options: Options<GetSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        getSignedRecordingRangeTranscriptionsTranscriptionIdRecordingsRecordingIdSignedUrlRangeGetQueryKey(
          options
        ),
    })
  }

export const recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostQueryKey =
  (
    options: Options<RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData>
  ) =>
    createQueryKey(
      'recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPost',
      options
    )

/**
 * Record Evidence Click
 */
export const recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostOptions =
  (
    options: Options<RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPost(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostQueryKey(
          options
        ),
    })
  }

/**
 * Record Evidence Click
 */
export const recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostMutation =
  (
    options?: Partial<
      Options<RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData>
    >
  ): UseMutationOptions<
    RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponse,
    RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostError,
    Options<RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostResponse,
      RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostError,
      Options<RecordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPostData>
    > = {
      mutationFn: async (localOptions) => {
        const { data } =
          await recordEvidenceClickTranscriptionsTranscriptionIdEvidenceClickPost(
            {
              ...options,
              ...localOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

export const getDialogueTranscriptionsTranscriptionIdDialogueGetQueryKey = (
  options: Options<GetDialogueTranscriptionsTranscriptionIdDialogueGetData>
) =>
  createQueryKey('getDialogueTranscriptionsTranscriptionIdDialogueGet', options)

/**
 * Get Dialogue
 */
export const getDialogueTranscriptionsTranscriptionIdDialogueGetOptions = (
  options: Options<GetDialogueTranscriptionsTranscriptionIdDialogueGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await getDialogueTranscriptionsTranscriptionIdDialogueGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        })
      return data
    },
    queryKey:
      getDialogueTranscriptionsTranscriptionIdDialogueGetQueryKey(options),
  })
}

/**
 * Update Dialogue
 */
export const updateDialogueTranscriptionsTranscriptionIdDialoguePatchMutation =
  (
    options?: Partial<
      Options<UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData>
    >
  ): UseMutationOptions<
    UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponse,
    UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchError,
    Options<UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData>
  > => {
    const mutationOptions: UseMutationOptions<
      UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchResponse,
      UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchError,
      Options<UpdateDialogueTranscriptionsTranscriptionIdDialoguePatchData>
    > = {
      mutationFn: async (localOptions) => {
        const { data } =
          await updateDialogueTranscriptionsTranscriptionIdDialoguePatch({
            ...options,
            ...localOptions,
            throwOnError: true,
          })
        return data
      },
    }
    return mutationOptions
  }

export const submitFeedbackTranscriptionsTranscriptionIdFeedbackPostQueryKey = (
  options: Options<SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData>
) =>
  createQueryKey(
    'submitFeedbackTranscriptionsTranscriptionIdFeedbackPost',
    options
  )

/**
 * Submit Feedback
 */
export const submitFeedbackTranscriptionsTranscriptionIdFeedbackPostOptions = (
  options: Options<SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await submitFeedbackTranscriptionsTranscriptionIdFeedbackPost({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        })
      return data
    },
    queryKey:
      submitFeedbackTranscriptionsTranscriptionIdFeedbackPostQueryKey(options),
  })
}

/**
 * Submit Feedback
 */
export const submitFeedbackTranscriptionsTranscriptionIdFeedbackPostMutation = (
  options?: Partial<
    Options<SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData>
  >
): UseMutationOptions<
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponse,
  SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostError,
  Options<SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostResponse,
    SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostError,
    Options<SubmitFeedbackTranscriptionsTranscriptionIdFeedbackPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await submitFeedbackTranscriptionsTranscriptionIdFeedbackPost({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getUserUsersMeGetQueryKey = (
  options?: Options<GetUserUsersMeGetData>
) => createQueryKey('getUserUsersMeGet', options)

/**
 * Get User
 */
export const getUserUsersMeGetOptions = (
  options?: Options<GetUserUsersMeGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserUsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserUsersMeGetQueryKey(options),
  })
}

/**
 * Update Data Retention
 * Update the data retention period for the current user.
 *
 * Args:
 * data: Request body containing data_retention_days
 * current_user: The current authenticated user
 */
export const updateDataRetentionUsersDataRetentionPatchMutation = (
  options?: Partial<Options<UpdateDataRetentionUsersDataRetentionPatchData>>
): UseMutationOptions<
  UpdateDataRetentionUsersDataRetentionPatchResponse,
  UpdateDataRetentionUsersDataRetentionPatchError,
  Options<UpdateDataRetentionUsersDataRetentionPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateDataRetentionUsersDataRetentionPatchResponse,
    UpdateDataRetentionUsersDataRetentionPatchError,
    Options<UpdateDataRetentionUsersDataRetentionPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateDataRetentionUsersDataRetentionPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) =>
    createQueryKey(
      'listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet',
      options
    )

/**
 * List Minutes For Transcription
 */
export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetOptions =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey(
          options
        ),
    })
  }

export const createMinuteTranscriptionTranscriptionIdMinutesPostQueryKey = (
  options: Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
) =>
  createQueryKey('createMinuteTranscriptionTranscriptionIdMinutesPost', options)

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPostOptions = (
  options: Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await createMinuteTranscriptionTranscriptionIdMinutesPost({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        })
      return data
    },
    queryKey:
      createMinuteTranscriptionTranscriptionIdMinutesPostQueryKey(options),
  })
}

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPostMutation = (
  options?: Partial<
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  >
): UseMutationOptions<
  unknown,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await createMinuteTranscriptionTranscriptionIdMinutesPost({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteMinutesMinutesIdGetQueryKey = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) => createQueryKey('getMinuteMinutesMinutesIdGet', options)

/**
 * Get Minute
 */
export const getMinuteMinutesMinutesIdGetOptions = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteMinutesMinutesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteMinutesMinutesIdGetQueryKey(options),
  })
}

export const listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) => createQueryKey('listMinuteVersionsMinutesMinuteIdVersionsGet', options)

/**
 * List Minute Versions
 */
export const listMinuteVersionsMinutesMinuteIdVersionsGetOptions = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMinuteVersionsMinutesMinuteIdVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey(options),
  })
}

export const createMinuteVersionMinutesMinuteIdVersionsPostQueryKey = (
  options: Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
) => createQueryKey('createMinuteVersionMinutesMinuteIdVersionsPost', options)

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPostOptions = (
  options: Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createMinuteVersionMinutesMinuteIdVersionsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createMinuteVersionMinutesMinuteIdVersionsPostQueryKey(options),
  })
}

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPostMutation = (
  options?: Partial<Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>>
): UseMutationOptions<
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
    CreateMinuteVersionMinutesMinuteIdVersionsPostError,
    Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createMinuteVersionMinutesMinuteIdVersionsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Minute Version
 */
export const deleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) => createQueryKey('getMinuteVersionMinuteVersionsMinuteVersionIdGet', options)

/**
 * Get Minute Version
 */
export const getMinuteVersionMinuteVersionsMinuteVersionIdGetOptions = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteVersionMinuteVersionsMinuteVersionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey(options),
  })
}

export const listMinuteTasksMinutesMinuteIdTasksGetQueryKey = (
  options: Options<ListMinuteTasksMinutesMinuteIdTasksGetData>
) => createQueryKey('listMinuteTasksMinutesMinuteIdTasksGet', options)

/**
 * List Minute Tasks
 */
export const listMinuteTasksMinutesMinuteIdTasksGetOptions = (
  options: Options<ListMinuteTasksMinutesMinuteIdTasksGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMinuteTasksMinutesMinuteIdTasksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMinuteTasksMinutesMinuteIdTasksGetQueryKey(options),
  })
}

export const createMinuteTaskMinutesMinuteIdTasksPostQueryKey = (
  options: Options<CreateMinuteTaskMinutesMinuteIdTasksPostData>
) => createQueryKey('createMinuteTaskMinutesMinuteIdTasksPost', options)

/**
 * Create Minute Task
 */
export const createMinuteTaskMinutesMinuteIdTasksPostOptions = (
  options: Options<CreateMinuteTaskMinutesMinuteIdTasksPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createMinuteTaskMinutesMinuteIdTasksPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createMinuteTaskMinutesMinuteIdTasksPostQueryKey(options),
  })
}

/**
 * Create Minute Task
 */
export const createMinuteTaskMinutesMinuteIdTasksPostMutation = (
  options?: Partial<Options<CreateMinuteTaskMinutesMinuteIdTasksPostData>>
): UseMutationOptions<
  CreateMinuteTaskMinutesMinuteIdTasksPostResponse,
  CreateMinuteTaskMinutesMinuteIdTasksPostError,
  Options<CreateMinuteTaskMinutesMinuteIdTasksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMinuteTaskMinutesMinuteIdTasksPostResponse,
    CreateMinuteTaskMinutesMinuteIdTasksPostError,
    Options<CreateMinuteTaskMinutesMinuteIdTasksPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createMinuteTaskMinutesMinuteIdTasksPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Patch Minute Task
 */
export const patchMinuteTaskMinutesMinuteIdTasksTaskIdPatchMutation = (
  options?: Partial<Options<PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData>>
): UseMutationOptions<
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchResponse,
  PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchError,
  Options<PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchResponse,
    PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchError,
    Options<PatchMinuteTaskMinutesMinuteIdTasksTaskIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchMinuteTaskMinutesMinuteIdTasksTaskIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const pushMinuteTasksMinutesMinuteIdTasksPushPostQueryKey = (
  options: Options<PushMinuteTasksMinutesMinuteIdTasksPushPostData>
) => createQueryKey('pushMinuteTasksMinutesMinuteIdTasksPushPost', options)

/**
 * Push Minute Tasks
 */
export const pushMinuteTasksMinutesMinuteIdTasksPushPostOptions = (
  options: Options<PushMinuteTasksMinutesMinuteIdTasksPushPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await pushMinuteTasksMinutesMinuteIdTasksPushPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: pushMinuteTasksMinutesMinuteIdTasksPushPostQueryKey(options),
  })
}

/**
 * Push Minute Tasks
 */
export const pushMinuteTasksMinutesMinuteIdTasksPushPostMutation = (
  options?: Partial<Options<PushMinuteTasksMinutesMinuteIdTasksPushPostData>>
): UseMutationOptions<
  PushMinuteTasksMinutesMinuteIdTasksPushPostResponse,
  PushMinuteTasksMinutesMinuteIdTasksPushPostError,
  Options<PushMinuteTasksMinutesMinuteIdTasksPushPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PushMinuteTasksMinutesMinuteIdTasksPushPostResponse,
    PushMinuteTasksMinutesMinuteIdTasksPushPostError,
    Options<PushMinuteTasksMinutesMinuteIdTasksPushPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await pushMinuteTasksMinutesMinuteIdTasksPushPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const exportMinuteMinutesMinuteIdExportPostQueryKey = (
  options: Options<ExportMinuteMinutesMinuteIdExportPostData>
) => createQueryKey('exportMinuteMinutesMinuteIdExportPost', options)

/**
 * Export Minute
 */
export const exportMinuteMinutesMinuteIdExportPostOptions = (
  options: Options<ExportMinuteMinutesMinuteIdExportPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await exportMinuteMinutesMinuteIdExportPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: exportMinuteMinutesMinuteIdExportPostQueryKey(options),
  })
}

/**
 * Export Minute
 */
export const exportMinuteMinutesMinuteIdExportPostMutation = (
  options?: Partial<Options<ExportMinuteMinutesMinuteIdExportPostData>>
): UseMutationOptions<
  ExportMinuteMinutesMinuteIdExportPostResponse,
  ExportMinuteMinutesMinuteIdExportPostError,
  Options<ExportMinuteMinutesMinuteIdExportPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ExportMinuteMinutesMinuteIdExportPostResponse,
    ExportMinuteMinutesMinuteIdExportPostError,
    Options<ExportMinuteMinutesMinuteIdExportPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await exportMinuteMinutesMinuteIdExportPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getTemplatesTemplatesGetQueryKey = (
  options?: Options<GetTemplatesTemplatesGetData>
) => createQueryKey('getTemplatesTemplatesGet', options)

/**
 * Get Templates
 * Get metadata for all templates.
 */
export const getTemplatesTemplatesGetOptions = (
  options?: Options<GetTemplatesTemplatesGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTemplatesTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTemplatesTemplatesGetQueryKey(options),
  })
}

export const getUserTemplatesUserTemplatesGetQueryKey = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) => createQueryKey('getUserTemplatesUserTemplatesGet', options)

/**
 * Get User Templates
 */
export const getUserTemplatesUserTemplatesGetOptions = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplatesUserTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplatesUserTemplatesGetQueryKey(options),
  })
}

export const createUserTemplateUserTemplatesPostQueryKey = (
  options: Options<CreateUserTemplateUserTemplatesPostData>
) => createQueryKey('createUserTemplateUserTemplatesPost', options)

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPostOptions = (
  options: Options<CreateUserTemplateUserTemplatesPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createUserTemplateUserTemplatesPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createUserTemplateUserTemplatesPostQueryKey(options),
  })
}

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPostMutation = (
  options?: Partial<Options<CreateUserTemplateUserTemplatesPostData>>
): UseMutationOptions<
  unknown,
  CreateUserTemplateUserTemplatesPostError,
  Options<CreateUserTemplateUserTemplatesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateUserTemplateUserTemplatesPostError,
    Options<CreateUserTemplateUserTemplatesPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createUserTemplateUserTemplatesPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete User Template
 */
export const deleteUserTemplateUserTemplatesTemplateIdDeleteMutation = (
  options?: Partial<
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteUserTemplateUserTemplatesTemplateIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getUserTemplateUserTemplatesTemplateIdGetQueryKey = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) => createQueryKey('getUserTemplateUserTemplatesTemplateIdGet', options)

/**
 * Get User Template
 */
export const getUserTemplateUserTemplatesTemplateIdGetOptions = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplateUserTemplatesTemplateIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplateUserTemplatesTemplateIdGetQueryKey(options),
  })
}

/**
 * Edit User Template
 */
export const editUserTemplateUserTemplatesTemplateIdPatchMutation = (
  options?: Partial<Options<EditUserTemplateUserTemplatesTemplateIdPatchData>>
): UseMutationOptions<
  unknown,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    EditUserTemplateUserTemplatesTemplateIdPatchError,
    Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await editUserTemplateUserTemplatesTemplateIdPatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostQueryKey =
  (
    options: Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
  ) =>
    createQueryKey(
      'duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost',
      options
    )

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostOptions =
  (
    options: Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true,
          })
        return data
      },
      queryKey:
        duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostQueryKey(
          options
        ),
    })
  }

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostMutation =
  (
    options?: Partial<
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    >
  ): UseMutationOptions<
    unknown,
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
    Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    > = {
      mutationFn: async (localOptions) => {
        const { data } =
          await duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost({
            ...options,
            ...localOptions,
            throwOnError: true,
          })
        return data
      },
    }
    return mutationOptions
  }

export const getTenantConfigConfigTenantIdGetQueryKey = (
  options: Options<GetTenantConfigConfigTenantIdGetData>
) => createQueryKey('getTenantConfigConfigTenantIdGet', options)

/**
 * Get Tenant Config
 */
export const getTenantConfigConfigTenantIdGetOptions = (
  options: Options<GetTenantConfigConfigTenantIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTenantConfigConfigTenantIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTenantConfigConfigTenantIdGetQueryKey(options),
  })
}

export const getUserModulesModulesGetQueryKey = (
  options?: Options<GetUserModulesModulesGetData>
) => createQueryKey('getUserModulesModulesGet', options)

/**
 * Get User Modules
 * Returns modules and navigation items for the current user's service_domain and role.
 *
 * Filters by:
 * - user.service_domain_id (from UserOrgRole table)
 * - user.role (from UserOrgRole table)
 * - tenant config (from config/{tenant}_{domain}.yaml)
 *
 * Returns:
 * - modules: List of enabled module IDs
 * - nav_items: List of navigation items with labels, hrefs, icons
 * - service_domain: Current user's domain
 * - role: Current user's role
 */
export const getUserModulesModulesGetOptions = (
  options?: Options<GetUserModulesModulesGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserModulesModulesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserModulesModulesGetQueryKey(options),
  })
}

export const checkAdminAccessAdminCheckAccessGetQueryKey = (
  options: Options<CheckAdminAccessAdminCheckAccessGetData>
) => createQueryKey('checkAdminAccessAdminCheckAccessGet', options)

/**
 * Check Admin Access
 * Check if current user has admin access.
 */
export const checkAdminAccessAdminCheckAccessGetOptions = (
  options: Options<CheckAdminAccessAdminCheckAccessGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkAdminAccessAdminCheckAccessGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: checkAdminAccessAdminCheckAccessGetQueryKey(options),
  })
}

export const listConfigsAdminConfigsGetQueryKey = (
  options: Options<ListConfigsAdminConfigsGetData>
) => createQueryKey('listConfigsAdminConfigsGet', options)

/**
 * List Configs
 * List all available tenant configurations.
 */
export const listConfigsAdminConfigsGetOptions = (
  options: Options<ListConfigsAdminConfigsGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listConfigsAdminConfigsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listConfigsAdminConfigsGetQueryKey(options),
  })
}

export const getConfigDetailAdminConfigsTenantIdGetQueryKey = (
  options: Options<GetConfigDetailAdminConfigsTenantIdGetData>
) => createQueryKey('getConfigDetailAdminConfigsTenantIdGet', options)

/**
 * Get Config Detail
 * Get detailed configuration for a specific tenant.
 */
export const getConfigDetailAdminConfigsTenantIdGetOptions = (
  options: Options<GetConfigDetailAdminConfigsTenantIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConfigDetailAdminConfigsTenantIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getConfigDetailAdminConfigsTenantIdGetQueryKey(options),
  })
}

export const getConfigAuditAdminConfigsTenantIdAuditGetQueryKey = (
  options: Options<GetConfigAuditAdminConfigsTenantIdAuditGetData>
) => createQueryKey('getConfigAuditAdminConfigsTenantIdAuditGet', options)

/**
 * Get Config Audit
 * Get audit trail for a specific tenant configuration.
 */
export const getConfigAuditAdminConfigsTenantIdAuditGetOptions = (
  options: Options<GetConfigAuditAdminConfigsTenantIdAuditGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConfigAuditAdminConfigsTenantIdAuditGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getConfigAuditAdminConfigsTenantIdAuditGetQueryKey(options),
  })
}

export const getConfigHistoryAdminConfigsTenantIdHistoryGetQueryKey = (
  options: Options<GetConfigHistoryAdminConfigsTenantIdHistoryGetData>
) => createQueryKey('getConfigHistoryAdminConfigsTenantIdHistoryGet', options)

/**
 * Get Config History
 * Get version history for a specific tenant configuration.
 */
export const getConfigHistoryAdminConfigsTenantIdHistoryGetOptions = (
  options: Options<GetConfigHistoryAdminConfigsTenantIdHistoryGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConfigHistoryAdminConfigsTenantIdHistoryGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getConfigHistoryAdminConfigsTenantIdHistoryGetQueryKey(options),
  })
}

export const listMyTasksTasksGetQueryKey = (
  options?: Options<ListMyTasksTasksGetData>
) => createQueryKey('listMyTasksTasksGet', options)

/**
 * List My Tasks
 */
export const listMyTasksTasksGetOptions = (
  options?: Options<ListMyTasksTasksGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMyTasksTasksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMyTasksTasksGetQueryKey(options),
  })
}

/**
 * Delete Chats
 */
export const deleteChatsTranscriptionsTranscriptionIdChatDeleteMutation = (
  options?: Partial<
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  >
): UseMutationOptions<
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteChatsTranscriptionsTranscriptionIdChatDelete(
        {
          ...options,
          ...localOptions,
          throwOnError: true,
        }
      )
      return data
    },
  }
  return mutationOptions
}

export const listChatTranscriptionsTranscriptionIdChatGetQueryKey = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) => createQueryKey('listChatTranscriptionsTranscriptionIdChatGet', options)

/**
 * List Chat
 */
export const listChatTranscriptionsTranscriptionIdChatGetOptions = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatTranscriptionsTranscriptionIdChatGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatTranscriptionsTranscriptionIdChatGetQueryKey(options),
  })
}

export const createChatTranscriptionsTranscriptionIdChatPostQueryKey = (
  options: Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
) => createQueryKey('createChatTranscriptionsTranscriptionIdChatPost', options)

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPostOptions = (
  options: Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createChatTranscriptionsTranscriptionIdChatPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createChatTranscriptionsTranscriptionIdChatPostQueryKey(options),
  })
}

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPostMutation = (
  options?: Partial<
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  >
): UseMutationOptions<
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateChatTranscriptionsTranscriptionIdChatPostResponse,
    CreateChatTranscriptionsTranscriptionIdChatPostError,
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createChatTranscriptionsTranscriptionIdChatPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Chat
 * Delete a specific transcription by ID.
 */
export const deleteChatTranscriptionsTranscriptionIdChatChatIdDeleteMutation = (
  options?: Partial<
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  >
): UseMutationOptions<
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } =
        await deleteChatTranscriptionsTranscriptionIdChatChatIdDelete({
          ...options,
          ...localOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) =>
  createQueryKey('getChatTranscriptionsTranscriptionIdChatChatIdGet', options)

/**
 * Get Chat
 */
export const getChatTranscriptionsTranscriptionIdChatChatIdGetOptions = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChatTranscriptionsTranscriptionIdChatChatIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey:
      getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey(options),
  })
}
